"""v7 profiles: the 120-byte binary protocol, firmware up to 7.x, port 47524.

One profile per model, two for HOME because its firmware revisions encode
byte[37] differently.  A feature listed here is one the model has; a
feature missing from a profile is one it does not have, and its field stays
None so no entity is created for it.  ``overrides`` name the reading to use
where this model's frame differs from the protocol default; everything else
uses the default reading from the feature's own file.

``evidence`` records why each entry is believed, in the words of the
captures, issues and the documents in docs/device analyzes/ that
established it.  "confirmed" means checked against the unit's display or the
Aseko Live app; "observed" means seen in real frames with plausible values but
not compared; "uncertain", "assumed" and "unverified" mean the earlier decoder
read it that way and nothing has contradicted it yet.  Every profile spells
its evidence out in full so that nothing is inherited from another model.
The support matrix in the docs is generated from these dictionaries.
"""

from __future__ import annotations

from ...aseko_data import AsekoDeviceType, AsekoFirmwareVariant, AsekoProfileFlag
from ..decoders import (
    AirTemperature,
    AlarmNoFlowToProbes,
    AlarmMaxDisinfectionDose,
    AlarmPhDosingIneffective,
    AlarmRapidPhChange,
    AlgaecidePumpRunning,
    FreezeProtectionEnabled,
    BackwashRunning,
    BackwashDuration,
    BackwashInterval,
    BackwashStartTime,
    FreeChlorine,
    FreeChlorineMv,
    ChlorinePumpRunning,
    Configuration,
    DosingDelay,
    StartupDelay,
    ElectrolysisRunning,
    ElectrodePolarity,
    ChlorineProduction,
    FiltrationRunning,
    FiltrationSchedule,
    FiltrationPeriod1Start,
    FiltrationPeriod2Start,
    FiltrationPeriod1End,
    FiltrationPeriod2End,
    FlocculantPumpRunning,
    AlgaecideFlowRate,
    ChlorineFlowRate,
    FlocculantFlowRate,
    OxygenFlowRate,
    PhMinusFlowRate,
    HeatingRunning,
    HeatingControlEnabled,
    MaxRefillTime,
    MaxPhDoses,
    OxygenPumpRunning,
    Ph,
    PhMinusConcentration,
    PhMinusPumpRunning,
    PoolVolume,
    Redox,
    AlgaecideDoseTarget,
    ChlorineDoseTarget,
    FreeChlorineTarget,
    FlocculantDoseTarget,
    OxygenDoseTarget,
    PhTarget,
    RedoxTarget,
    WaterTemperatureTarget,
    Salinity,
    SerialNumber,
    ServiceMenuOpen,
    Timestamp,
    VariableSpeedPumpRunning,
    Refilling,
    WaterFlowToProbes,
    WaterLevel,
    WaterLevelRefillStop,
    WaterLevelRefillStart,
    WaterLevelHighAlarm,
    WaterLevelLowAlarm,
    WaterTemperature,
)
from ..frame import Protocol
from ..profile import Profile

# ---------------------------------------------------------------------------
# Feature groups shared between profiles.  A group is a convenience for
# reading the lists below, not a concept the decoder knows.
# ---------------------------------------------------------------------------

_IDENTITY = (SerialNumber, Configuration, Timestamp)
_MEASUREMENTS = (WaterTemperature, WaterFlowToProbes)
_CHLORINE_PROBES = (Ph, Redox, FreeChlorine, FreeChlorineMv)
_SETTINGS = (
    PhTarget,
    WaterTemperatureTarget,
    PoolVolume,
    StartupDelay,
    DosingDelay,
    PhMinusFlowRate,
)
_ALARMS = (
    AlarmPhDosingIneffective,
    AlarmMaxDisinfectionDose,
    AlarmNoFlowToProbes,
    AlarmRapidPhChange,
)
_FILTRATION = (
    FiltrationPeriod1Start,
    FiltrationPeriod1End,
    FiltrationPeriod2Start,
    FiltrationPeriod2End,
    FiltrationSchedule,
    FiltrationRunning,
)
_BACKWASH = (BackwashInterval, BackwashStartTime, BackwashDuration, BackwashRunning)
_WATER_LEVEL = (
    WaterLevel,
    WaterLevelLowAlarm,
    WaterLevelRefillStart,
    WaterLevelRefillStop,
    WaterLevelHighAlarm,
    Refilling,
)
_UNIT_STATE = (HeatingRunning, VariableSpeedPumpRunning, PhMinusConcentration)

# The disinfection setpoint family on chlorine units: byte[53] is one of
# these three depending on the installed probes, each answers only when it
# is the one that applies.
_DISINFECTION_SETPOINTS = (FreeChlorineTarget, RedoxTarget, ChlorineDoseTarget)

# Algicide / flocculant on a single shared port, routed by byte[37] bit 0x80.
_SHARED_THIRD_PUMP = {
    AlgaecideDoseTarget: "decode_v7_routed_by_byte37",
    FlocculantDoseTarget: "decode_v7_routed_by_byte37",
    AlgaecideFlowRate: "decode_v7_routed_by_byte37",
    FlocculantFlowRate: "decode_v7_routed_by_byte37",
}

# ---------------------------------------------------------------------------
# SALT
# ---------------------------------------------------------------------------

SALT = Profile(
    name="v7 SALT",
    protocol=Protocol.V7,
    model=AsekoDeviceType.SALT,
    features=(
        *_IDENTITY,
        *_MEASUREMENTS,
        AirTemperature,
        *_CHLORINE_PROBES,
        Salinity,
        ChlorineProduction,
        ElectrolysisRunning,
        ElectrodePolarity,
        *_SETTINGS,
        *_DISINFECTION_SETPOINTS,
        AlgaecideDoseTarget,
        FlocculantDoseTarget,
        AlgaecideFlowRate,
        FlocculantFlowRate,
        *_FILTRATION,
        ServiceMenuOpen,
        PhMinusPumpRunning,
        AlgaecidePumpRunning,
        FlocculantPumpRunning,
        *_WATER_LEVEL,
        MaxRefillTime,
        MaxPhDoses,
        *_UNIT_STATE,
        HeatingControlEnabled,
        FreezeProtectionEnabled,
        *_BACKWASH,
        *_ALARMS,
    ),
    overrides={
        **_SHARED_THIRD_PUMP,
        HeatingControlEnabled: "decode_v7_not_located",
        FreezeProtectionEnabled: "decode_v7_not_located",
    },
    flags=frozenset({AsekoProfileFlag.MENU_BIT_IS_PRESENCE_ONLY}),
    evidence={
        AirTemperature: "confirmed: two dumps from one SALT vs the unit display (Issue #155); matches the app and unit display, 2026-09-11",
        AlarmNoFlowToProbes: "confirmed: byte[13] 0x04 (DomSchCoding, NET frame)",
        AlarmMaxDisinfectionDose: "confirmed on HOME: byte[12] 0x20 (Issue #134), byte[13] 0x01 (Issue #151)",
        AlarmPhDosingIneffective: "confirmed on HOME: byte[12] 0x40 (Issue #134); byte[13] 0x02 inferred",
        AlarmRapidPhChange: "unconfirmed: byte[13] 0x08 from error_codes.md; never set in the own SALT dumps, 37 frames 2026-08-08..28",
        AlgaecidePumpRunning: "confirmed: byte[29] 0x20, 27 frames (PR #87)",
        FreezeProtectionEnabled: "not located: the unit's Configuration menu has Winter mode ON/OFF; HOME's byte[37] 0x80 is the algicide routing on SALT, so it lives elsewhere",
        BackwashRunning: "confirmed: byte[29] 0x01, 2026-08-11 capture of a manual backwash",
        BackwashDuration: "confirmed: byte[71] * 10 matched the relay window; matches the app and unit display, 2026-09-11",
        BackwashInterval: "confirmed: byte[68] vs the unit's backwash settings (own SALT, the v1.8.0 backwash tracker classifies cycles against it); matches the app and unit display, 2026-09-11",
        BackwashStartTime: "confirmed: bytes 69-70 vs the unit's backwash settings (own SALT, v1.8.0 backwash tracker); matches the app and unit display, 2026-09-11",
        FreeChlorine: "confirmed: bytes 16-17 = 0.77 and 0.93 mg/l on the CLF unit of the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer",
        FreeChlorineMv: "confirmed: bytes 20-21 = 6656 and 6934 mV on the CLF unit of the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer",
        Configuration: "confirmed: byte[4] missing-probe bits (0x0D CLF, 0x0E REDOX, 0x0F DOSE); matches the app and unit display, 2026-09-11",
        DosingDelay: "confirmed: bytes 106-107; matches the app and unit display, 2026-09-11",
        StartupDelay: "confirmed: bytes 74-75; matches the app and unit display, 2026-09-11",
        ElectrolysisRunning: "confirmed: byte[29] 0x10, 25 frames (PR #87)",
        ElectrodePolarity: "confirmed: left, right and waiting all seen (own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer); matches the app and unit display, 2026-09-11",
        ChlorineProduction: "confirmed: byte[21] while 0x10 set (PR #87); matches the app and unit display, 2026-09-11",
        FiltrationRunning: "confirmed: byte[29] 0x08 in every active phase (PR #87)",
        FiltrationSchedule: "confirmed: 0xC3 / 0xD3 / 0xF3, every transition both ways; matches the app and unit display, 2026-09-11",
        FlocculantPumpRunning: "confirmed: byte[29] 0x20, Apr 3 frames",
        AlgaecideFlowRate: "confirmed: byte[101] via byte[37] 0x80 (Issue #84, SALT v5.0, shows 0x13 with bit 7 clear while set to algicide: an older firmware may route differently)",
        FlocculantFlowRate: "confirmed: byte[101] via byte[37] 0x80 clear (Issue #84, SALT v5.0, shows 0x13 with bit 7 clear while set to algicide: an older firmware may route differently)",
        PhMinusFlowRate: "confirmed: byte[95] (Issue #110, #115)",
        HeatingRunning: "assumed: byte[29] 0x04 per JS-DE-Tech relay_byte bit 2; never set in the own SALT dumps, whose unit has heating control OFF",
        HeatingControlEnabled: "not located: the unit's Configuration menu has Heating control ON/OFF; HOME's byte[37] 0x08 was clear in every own SALT frame with it OFF, the ON state was never captured",
        MaxRefillTime: "confirmed: bytes 76-77 vs Aseko Live (1800 s = 30 min); matches the app and unit display, 2026-09-11",
        MaxPhDoses: "confirmed: byte[115] followed a change of the unit's Safety Functions setting from 20 to 17 on the REDOX unit, 2026-09-12 19:47 -- and 17 appears nowhere else in that frame; 40 on the CLF unit",
        Ph: "confirmed: bytes 14-15 / 100 on every model",
        PhMinusConcentration: "confirmed: byte[112] = 14 then 15 % in the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer; matches the app and unit display, 2026-09-11",
        PhMinusPumpRunning: "unconfirmed: byte[29] 0x80; the bit was never set in the own SALT dumps, 37 frames 2026-08-08..28",
        PoolVolume: "confirmed: bytes 92-93; matches the app and unit display, 2026-09-11",
        Redox: "confirmed: bytes 16-19 = 593..670 mV on the REDOX unit of the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer",
        AlgaecideDoseTarget: "confirmed: byte[54] via byte[37] 0x80 (@hopkins-tk, Issue #84) (Issue #84, SALT v5.0, shows 0x13 with bit 7 clear while set to algicide: an older firmware may route differently); matches the app and unit display, 2026-09-11",
        ChlorineDoseTarget: "unverified: byte[53] for a DOSE unit; neither unit of the own SALT dumps, 37 frames 2026-08-08..28 is one",
        FreeChlorineTarget: "confirmed: byte[53] / 10 = 0.9 mg/l on the CLF unit of the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer",
        FlocculantDoseTarget: "confirmed: byte[54] via byte[37] 0x80 clear (Issue #84, SALT v5.0, shows 0x13 with bit 7 clear while set to algicide: an older firmware may route differently)",
        PhTarget: "confirmed: byte[52] / 10 on every model; matches the app and unit display, 2026-09-11",
        RedoxTarget: "confirmed: byte[53] * 10 = 670 mV on the REDOX unit of the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer; matches the app and unit display, 2026-09-11",
        WaterTemperatureTarget: "confirmed: byte[55] = 25 C in every frame (own SALT dumps Aug 2026); the app shows --- while heating control is OFF, so the byte keeps the setpoint the app hides",
        Salinity: "confirmed: byte[20] / 10; matches the app and unit display, 2026-09-11",
        SerialNumber: "confirmed: bytes 0-3, repeated in every segment header",
        ServiceMenuOpen: "confirmed: 0xD7 / 0xF7 then the unit goes offline",
        FiltrationPeriod1Start: "confirmed: bytes 56-57 changed 08:00 -> 09:00 with the timer settings during the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer; matches the app and unit display, 2026-09-11",
        FiltrationPeriod2Start: "confirmed: bytes 60-61 changed 18:00 -> 18:10 with the timer settings during the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer; matches the app and unit display, 2026-09-11",
        FiltrationPeriod1End: "confirmed: bytes 58-59 changed 18:05 / 19:00 / 21:35 with the timer settings during the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer; matches the app and unit display, 2026-09-11",
        FiltrationPeriod2End: "confirmed: bytes 62-63 changed 22:00 -> 23:55 with the timer settings during the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer; matches the app and unit display, 2026-09-11",
        Timestamp: "confirmed: bytes 6-11",
        VariableSpeedPumpRunning: "confirmed: byte[22] bit 0x08 clear on the REDOX unit (display: VS Pump OFF) and set on the CLF one; own SALT dumps Aug 2026, checked against the unit by the maintainer",
        Refilling: "assumed: byte[29] 0x02, confirmed on HOME only; never set in the own SALT dumps, 37 frames 2026-08-08..28",
        WaterFlowToProbes: "confirmed: byte[28] == 0xAA",
        WaterLevel: "confirmed: byte[27] 14..25 cm across the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer",
        WaterLevelRefillStop: "confirmed: byte[104] = 25 and 35 cm on the two units of the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer; matches the app and unit display, 2026-09-11",
        WaterLevelRefillStart: "confirmed: byte[103] = 10 and 33 cm on the two units of the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer; matches the app and unit display, 2026-09-11",
        WaterLevelHighAlarm: "confirmed: byte[105] = 40 and 56..73 cm on the two units of the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer; matches the app and unit display, 2026-09-11",
        WaterLevelLowAlarm: "confirmed: byte[102] = 5 and 31 cm on the two units of the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer; thresholds ordered low < on < off < high; matches the app and unit display, 2026-09-11",
        WaterTemperature: "confirmed: bytes 25-26 / 10 on every model",
    },
)

# ---------------------------------------------------------------------------
# HOME, two firmware revisions
# ---------------------------------------------------------------------------

_HOME_FEATURES = (
    *_IDENTITY,
    *_MEASUREMENTS,
    AirTemperature,
    *_CHLORINE_PROBES,
    *_SETTINGS,
    *_DISINFECTION_SETPOINTS,
    AlgaecideDoseTarget,
    FlocculantDoseTarget,
    ChlorineFlowRate,
    AlgaecideFlowRate,
    FlocculantFlowRate,
    *_FILTRATION,
    ChlorinePumpRunning,
    PhMinusPumpRunning,
    AlgaecidePumpRunning,
    FlocculantPumpRunning,
    *_WATER_LEVEL,
    MaxRefillTime,
    MaxPhDoses,
    *_UNIT_STATE,
    HeatingControlEnabled,
    FreezeProtectionEnabled,
    *_BACKWASH,
    *_ALARMS,
)

HOME_A = Profile(
    name="v7 HOME firmware A",
    protocol=Protocol.V7,
    model=AsekoDeviceType.HOME,
    firmware=AsekoFirmwareVariant.HOME_A,
    features=_HOME_FEATURES,
    overrides={
        Configuration: "decode_v7_by_unit_type_byte",
        FiltrationSchedule: "decode_v7_home_a",
    },
    evidence={
        AirTemperature: "unverified: bytes 23-24 = 0xFE70 (no air probe, the SALT marker) in every captured HOME frame, so no entity yet; the Aseko Live app shows air temperature on HOME units",
        AlarmNoFlowToProbes: "confirmed: byte[13] 0x04 (DomSchCoding, NET frame)",
        AlarmMaxDisinfectionDose: "confirmed on HOME: byte[12] 0x20 (Issue #134), byte[13] 0x01 (Issue #151)",
        AlarmPhDosingIneffective: "confirmed on HOME: byte[12] 0x40 (Issue #134); byte[13] 0x02 inferred",
        AlarmRapidPhChange: "unconfirmed: byte[13] 0x08 was set on serial 110128063 with no matching alarm known in the app",
        AlgaecidePumpRunning: "uncertain: byte[29] 0x20 assumed",
        FreezeProtectionEnabled: "confirmed: byte[37] 0x80, serial 110175608 (Issue #136)",
        BackwashRunning: "assumed: byte[29] 0x01, confirmed on SALT",
        BackwashDuration: "confirmed: byte[71] * 10 = 120 s vs '02:00 min' in Aseko Live, serial 110128063",
        BackwashInterval: "confirmed: byte[68] = 3 vs 'every 3 days' in Aseko Live, serial 110128063",
        BackwashStartTime: "confirmed: bytes 69-70 = 21:00 vs Aseko Live, serial 110128063",
        FreeChlorine: "confirmed: bytes 16-17 = 0.00 mg/l vs Aseko Live, serial 110128063 (2026-04-28)",
        FreeChlorineMv: "confirmed: bytes 20-21 = 2 mV, serial 110128063 (2026-04-28)",
        ChlorinePumpRunning: "uncertain: byte[29] 0x40, port may be chlorine or OXY Pure",
        Configuration: "confirmed: byte[4] exact sub-type, 0x02 CLF / 0x03 REDOX (Issue #110)",
        DosingDelay: "confirmed: bytes 106-107 = 240 s vs '4 min' in Aseko Live, serial 110128063",
        StartupDelay: "confirmed: bytes 74-75 = 480 s vs '8 min' in Aseko Live, serial 110128063",
        FiltrationRunning: "observed: byte[29] 0x08 clear while Aseko Live showed STOP, serial 110128063; the set state was not captured on firmware A",
        FiltrationSchedule: "confirmed: 0x43 nonstop / 0x53 timer, serial 110128063; fallback for 0x41 / 0x45 / 0x49 (Issue #135)",
        FlocculantPumpRunning: "uncertain: byte[29] 0x20 assumed",
        AlgaecideFlowRate: "confirmed: byte[103], Issues #110, #115 -- but the same byte is also read as water_level_refill_start, and one of the two must be wrong",
        ChlorineFlowRate: "confirmed: byte[99], serials 110071590 / 110128063 (Issues #110, #115)",
        FlocculantFlowRate: "confirmed: byte[101], Issues #110, #115",
        PhMinusFlowRate: "confirmed: byte[95] = 60, Aseko Live lists the pH- pump, serial 110128063",
        HeatingRunning: "assumed: byte[29] 0x04 per JS-DE-Tech relay_byte bit 2; no HOME frame with the heater running (open item 9)",
        HeatingControlEnabled: "confirmed: byte[37] 0x08, serial 110175608 (Issue #135)",
        MaxRefillTime: "assumed: bytes 76-77 = 10800 s on serial 110128063, plausible (180 min); verified on SALT only",
        MaxPhDoses: "observed: byte[115] = 20 on serial 110128063; the position is confirmed on SALT, the HOME setting was never compared",
        Ph: "confirmed: bytes 14-15 = 6.29 vs 6.56 in Aseko Live (later reading), serial 110128063",
        PhMinusConcentration: "confirmed: byte[112], serial 110175608 (Issue #139)",
        PhMinusPumpRunning: "uncertain: byte[29] 0x80 assumed",
        PoolVolume: "confirmed: bytes 92-93 = 60 m3 vs Aseko Live, serial 110128063",
        AlgaecideDoseTarget: "confirmed: byte[72], serial 110128063 (2026-04-28)",
        FreeChlorineTarget: "confirmed: byte[53] / 10 = 0.3 mg/l vs Aseko Live, serial 110128063",
        FlocculantDoseTarget: "confirmed: byte[54], serial 110128063 (2026-04-28)",
        PhTarget: "confirmed: byte[52] / 10 = 7.0 vs Aseko Live, serial 110128063",
        WaterTemperatureTarget: "confirmed: byte[55] is the heating setpoint on serial 110175608 (Issue #135); 25 C with heating disabled on 110128063",
        SerialNumber: "confirmed: bytes 0-3, repeated in every segment header",
        FiltrationPeriod1Start: "confirmed: bytes 56-57 = 08:00 last-configured, serial 110128063 (Issues #110, #133)",
        FiltrationPeriod2Start: "confirmed: bytes 60-61 = 18:00 last-configured, serial 110128063 (Issues #110, #133)",
        FiltrationPeriod1End: "confirmed: bytes 58-59 = 16:00 last-configured, serial 110128063 (Issues #110, #133)",
        FiltrationPeriod2End: "confirmed: bytes 62-63 = 22:00 last-configured, serial 110128063 (Issues #110, #133)",
        Timestamp: "confirmed: bytes 6-11",
        VariableSpeedPumpRunning: "confirmed: byte[22] 0x08, serial 110175608",
        Refilling: "confirmed: byte[29] 0x02 (DomSchCoding #100)",
        WaterFlowToProbes: "confirmed: byte[28] != 0xAA while Aseko Live showed 'NO', serial 110128063",
        WaterLevel: "confirmed: byte[27] (domin211, Issue #110)",
        WaterLevelRefillStop: "confirmed: byte[104] (domin211, DomSchCoding, Issue #110)",
        WaterLevelRefillStart: "unconfirmed: byte[103] = 33 on serial 110128063 is read both as this threshold (cm) and as algaecide_flow_rate (ml/min); the two mappings cannot both be right",
        WaterLevelHighAlarm: "confirmed: byte[105] (domin211, Issue #110)",
        WaterLevelLowAlarm: "confirmed: byte[102] (domin211, Issue #110)",
        WaterTemperature: "confirmed: bytes 25-26 = 37.9 C vs 38.2 C in Aseko Live (later reading), serial 110128063",
    },
)

HOME_B = Profile(
    name="v7 HOME firmware B",
    protocol=Protocol.V7,
    model=AsekoDeviceType.HOME,
    firmware=AsekoFirmwareVariant.HOME_B,
    features=(*_HOME_FEATURES, ServiceMenuOpen),
    overrides={
        Configuration: "decode_v7_by_unit_type_byte",
        FiltrationRunning: "decode_v7_menu_override",
    },
    evidence={
        AirTemperature: "unverified: bytes 23-24 = 0xFE70 (no air probe, the SALT marker) in every captured HOME frame, so no entity yet; the Aseko Live app shows air temperature on HOME units",
        AlarmNoFlowToProbes: "confirmed: byte[13] 0x04 (DomSchCoding, NET frame)",
        AlarmMaxDisinfectionDose: "confirmed on HOME: byte[12] 0x20 (Issue #134), byte[13] 0x01 (Issue #151)",
        AlarmPhDosingIneffective: "confirmed on HOME: byte[12] 0x40 (Issue #134); byte[13] 0x02 inferred",
        AlarmRapidPhChange: "unconfirmed: byte[13] 0x08 was set on serial 110128063 with no matching alarm known in the app",
        AlgaecidePumpRunning: "uncertain: byte[29] 0x20 assumed",
        FreezeProtectionEnabled: "unverified: byte[37] 0x80 read as on firmware A, no capture on B",
        BackwashRunning: "assumed: byte[29] 0x01, confirmed on SALT",
        BackwashDuration: "confirmed: byte[71] * 10 = 120 s vs '02:00 min' in Aseko Live, serial 110128063",
        BackwashInterval: "confirmed: byte[68] = 3 vs 'every 3 days' in Aseko Live, serial 110128063",
        BackwashStartTime: "confirmed: bytes 69-70 = 21:00 vs Aseko Live, serial 110128063",
        FreeChlorine: "confirmed: bytes 16-17 = 0.00 mg/l vs Aseko Live, serial 110128063 (2026-04-28)",
        FreeChlorineMv: "confirmed: bytes 20-21 = 2 mV, serial 110128063 (2026-04-28)",
        ChlorinePumpRunning: "uncertain: byte[29] 0x40, port may be chlorine or OXY Pure",
        Configuration: "confirmed: byte[4] exact sub-type, 0x02 CLF / 0x03 REDOX (Issue #110)",
        DosingDelay: "confirmed: bytes 106-107 = 240 s vs '4 min' in Aseko Live, serial 110128063",
        StartupDelay: "confirmed: bytes 74-75 = 480 s vs '8 min' in Aseko Live, serial 110128063",
        FiltrationRunning: "confirmed: byte[29] 0x08 stays set under the override, so 0x04 wins (Issue #133)",
        FiltrationSchedule: "confirmed: 0x01 / 0x11 / 0x31, serial 110169464 (Issue #133)",
        FlocculantPumpRunning: "uncertain: byte[29] 0x20 assumed",
        AlgaecideFlowRate: "confirmed: byte[103], Issues #110, #115 -- but the same byte is also read as water_level_refill_start, and one of the two must be wrong",
        ChlorineFlowRate: "confirmed: byte[99], serials 110071590 / 110128063 (Issues #110, #115)",
        FlocculantFlowRate: "confirmed: byte[101], Issues #110, #115",
        PhMinusFlowRate: "confirmed: byte[95] = 60, Aseko Live lists the pH- pump, serial 110128063",
        HeatingRunning: "assumed: byte[29] 0x04 per JS-DE-Tech relay_byte bit 2; no HOME frame with the heater running (open item 9)",
        HeatingControlEnabled: "unverified: byte[37] 0x08 read as on firmware A, no capture on B",
        MaxRefillTime: "assumed: bytes 76-77 = 10800 s on serial 110128063, plausible (180 min); verified on SALT only",
        MaxPhDoses: "observed: byte[115] = 20 on serial 110128063; the position is confirmed on SALT, the HOME setting was never compared",
        Ph: "confirmed: bytes 14-15 = 6.29 vs 6.56 in Aseko Live (later reading), serial 110128063",
        PhMinusConcentration: "confirmed: byte[112], serial 110175608 (Issue #139)",
        PhMinusPumpRunning: "uncertain: byte[29] 0x80 assumed",
        PoolVolume: "confirmed: bytes 92-93 = 60 m3 vs Aseko Live, serial 110128063",
        AlgaecideDoseTarget: "confirmed: byte[72], serial 110128063 (2026-04-28)",
        FreeChlorineTarget: "confirmed: byte[53] / 10 = 0.3 mg/l vs Aseko Live, serial 110128063",
        FlocculantDoseTarget: "confirmed: byte[54], serial 110128063 (2026-04-28)",
        PhTarget: "confirmed: byte[52] / 10 = 7.0 vs Aseko Live, serial 110128063",
        WaterTemperatureTarget: "confirmed: byte[55] is the heating setpoint on serial 110175608 (Issue #135); 25 C with heating disabled on 110128063",
        SerialNumber: "confirmed: bytes 0-3, repeated in every segment header",
        ServiceMenuOpen: "confirmed: byte[37] 0x04 as a standing pump override (Issue #133)",
        FiltrationPeriod1Start: "confirmed: bytes 56-57 = 08:00 last-configured, serial 110128063 (Issues #110, #133)",
        FiltrationPeriod2Start: "confirmed: bytes 60-61 = 18:00 last-configured, serial 110128063 (Issues #110, #133)",
        FiltrationPeriod1End: "confirmed: bytes 58-59 = 16:00 last-configured, serial 110128063 (Issues #110, #133)",
        FiltrationPeriod2End: "confirmed: bytes 62-63 = 22:00 last-configured, serial 110128063 (Issues #110, #133)",
        Timestamp: "confirmed: bytes 6-11",
        VariableSpeedPumpRunning: "confirmed: byte[22] 0x08, serial 110175608",
        Refilling: "confirmed: byte[29] 0x02 (DomSchCoding #100)",
        WaterFlowToProbes: "confirmed: byte[28] != 0xAA while Aseko Live showed 'NO', serial 110128063",
        WaterLevel: "confirmed: byte[27] (domin211, Issue #110)",
        WaterLevelRefillStop: "confirmed: byte[104] (domin211, DomSchCoding, Issue #110)",
        WaterLevelRefillStart: "unconfirmed: byte[103] = 33 on serial 110128063 is read both as this threshold (cm) and as algaecide_flow_rate (ml/min); the two mappings cannot both be right",
        WaterLevelHighAlarm: "confirmed: byte[105] (domin211, Issue #110)",
        WaterLevelLowAlarm: "confirmed: byte[102] (domin211, Issue #110)",
        WaterTemperature: "confirmed: bytes 25-26 = 37.9 C vs 38.2 C in Aseko Live (later reading), serial 110128063",
    },
)

# A HOME frame with byte[37] unset says nothing about its firmware.  Read
# what both revisions share and nothing that only one of them has, so that no
# entity is created on the strength of a guess: service_menu_open exists only
# on firmware B and is left out.  Every byte[37] reading returns "unknown"
# on such a frame anyway, so the values cannot differ from either revision.
HOME_UNKNOWN_FIRMWARE = Profile(
    name="v7 HOME firmware not yet known",
    protocol=Protocol.V7,
    model=AsekoDeviceType.HOME,
    features=_HOME_FEATURES,
    overrides={Configuration: "decode_v7_by_unit_type_byte"},
    evidence={
        AirTemperature: "unverified: bytes 23-24 = 0xFE70 (no air probe, the SALT marker) in every captured HOME frame, so no entity yet; the Aseko Live app shows air temperature on HOME units",
        AlarmNoFlowToProbes: "confirmed: byte[13] 0x04 (DomSchCoding, NET frame)",
        AlarmMaxDisinfectionDose: "confirmed on HOME: byte[12] 0x20 (Issue #134), byte[13] 0x01 (Issue #151)",
        AlarmPhDosingIneffective: "confirmed on HOME: byte[12] 0x40 (Issue #134); byte[13] 0x02 inferred",
        AlarmRapidPhChange: "unconfirmed: byte[13] 0x08 was set on serial 110128063 with no matching alarm known in the app",
        AlgaecidePumpRunning: "uncertain: byte[29] 0x20 assumed",
        FreezeProtectionEnabled: "n/a: byte[37] is unset on every frame decoded with this profile",
        BackwashRunning: "assumed: byte[29] 0x01, confirmed on SALT",
        BackwashDuration: "confirmed: byte[71] * 10 = 120 s vs '02:00 min' in Aseko Live, serial 110128063",
        BackwashInterval: "confirmed: byte[68] = 3 vs 'every 3 days' in Aseko Live, serial 110128063",
        BackwashStartTime: "confirmed: bytes 69-70 = 21:00 vs Aseko Live, serial 110128063",
        FreeChlorine: "confirmed: bytes 16-17 = 0.00 mg/l vs Aseko Live, serial 110128063 (2026-04-28)",
        FreeChlorineMv: "confirmed: bytes 20-21 = 2 mV, serial 110128063 (2026-04-28)",
        ChlorinePumpRunning: "uncertain: byte[29] 0x40, port may be chlorine or OXY Pure",
        Configuration: "confirmed: byte[4] exact sub-type, 0x02 CLF / 0x03 REDOX (Issue #110)",
        DosingDelay: "confirmed: bytes 106-107 = 240 s vs '4 min' in Aseko Live, serial 110128063",
        StartupDelay: "confirmed: bytes 74-75 = 480 s vs '8 min' in Aseko Live, serial 110128063",
        FiltrationRunning: "observed: byte[29] 0x08 clear while Aseko Live showed STOP, serial 110128063; the set state was not captured on firmware A",
        FiltrationSchedule: "n/a: byte[37] is unset on every frame decoded with this profile",
        FlocculantPumpRunning: "uncertain: byte[29] 0x20 assumed",
        AlgaecideFlowRate: "confirmed: byte[103], Issues #110, #115 -- but the same byte is also read as water_level_refill_start, and one of the two must be wrong",
        ChlorineFlowRate: "confirmed: byte[99], serials 110071590 / 110128063 (Issues #110, #115)",
        FlocculantFlowRate: "confirmed: byte[101], Issues #110, #115",
        PhMinusFlowRate: "confirmed: byte[95] = 60, Aseko Live lists the pH- pump, serial 110128063",
        HeatingRunning: "assumed: byte[29] 0x04 per JS-DE-Tech relay_byte bit 2; no HOME frame with the heater running (open item 9)",
        HeatingControlEnabled: "n/a: byte[37] is unset on every frame decoded with this profile",
        MaxRefillTime: "assumed: bytes 76-77 = 10800 s on serial 110128063, plausible (180 min); verified on SALT only",
        MaxPhDoses: "observed: byte[115] = 20 on serial 110128063; the position is confirmed on SALT, the HOME setting was never compared",
        Ph: "confirmed: bytes 14-15 = 6.29 vs 6.56 in Aseko Live (later reading), serial 110128063",
        PhMinusConcentration: "confirmed: byte[112], serial 110175608 (Issue #139)",
        PhMinusPumpRunning: "uncertain: byte[29] 0x80 assumed",
        PoolVolume: "confirmed: bytes 92-93 = 60 m3 vs Aseko Live, serial 110128063",
        AlgaecideDoseTarget: "confirmed: byte[72], serial 110128063 (2026-04-28)",
        FreeChlorineTarget: "confirmed: byte[53] / 10 = 0.3 mg/l vs Aseko Live, serial 110128063",
        FlocculantDoseTarget: "confirmed: byte[54], serial 110128063 (2026-04-28)",
        PhTarget: "confirmed: byte[52] / 10 = 7.0 vs Aseko Live, serial 110128063",
        WaterTemperatureTarget: "confirmed: byte[55] is the heating setpoint on serial 110175608 (Issue #135); 25 C with heating disabled on 110128063",
        SerialNumber: "confirmed: bytes 0-3, repeated in every segment header",
        FiltrationPeriod1Start: "confirmed: bytes 56-57 = 08:00 last-configured, serial 110128063 (Issues #110, #133)",
        FiltrationPeriod2Start: "confirmed: bytes 60-61 = 18:00 last-configured, serial 110128063 (Issues #110, #133)",
        FiltrationPeriod1End: "confirmed: bytes 58-59 = 16:00 last-configured, serial 110128063 (Issues #110, #133)",
        FiltrationPeriod2End: "confirmed: bytes 62-63 = 22:00 last-configured, serial 110128063 (Issues #110, #133)",
        Timestamp: "confirmed: bytes 6-11",
        VariableSpeedPumpRunning: "confirmed: byte[22] 0x08, serial 110175608",
        Refilling: "confirmed: byte[29] 0x02 (DomSchCoding #100)",
        WaterFlowToProbes: "confirmed: byte[28] != 0xAA while Aseko Live showed 'NO', serial 110128063",
        WaterLevel: "confirmed: byte[27] (domin211, Issue #110)",
        WaterLevelRefillStop: "confirmed: byte[104] (domin211, DomSchCoding, Issue #110)",
        WaterLevelRefillStart: "unconfirmed: byte[103] = 33 on serial 110128063 is read both as this threshold (cm) and as algaecide_flow_rate (ml/min); the two mappings cannot both be right",
        WaterLevelHighAlarm: "confirmed: byte[105] (domin211, Issue #110)",
        WaterLevelLowAlarm: "confirmed: byte[102] (domin211, Issue #110)",
        WaterTemperature: "confirmed: bytes 25-26 = 37.9 C vs 38.2 C in Aseko Live (later reading), serial 110128063",
    },
)

# ---------------------------------------------------------------------------
# OXY (ASIN AQUA Oxygen)
# ---------------------------------------------------------------------------

OXY = Profile(
    name="v7 OXY",
    protocol=Protocol.V7,
    model=AsekoDeviceType.OXY,
    features=(
        *_IDENTITY,
        *_MEASUREMENTS,
        AirTemperature,
        Ph,
        *_SETTINGS,
        OxygenDoseTarget,
        FlocculantDoseTarget,
        AlgaecideDoseTarget,
        OxygenFlowRate,
        FlocculantFlowRate,
        AlgaecideFlowRate,
        *_FILTRATION,
        ServiceMenuOpen,
        PhMinusPumpRunning,
        AlgaecidePumpRunning,
        FlocculantPumpRunning,
        OxygenPumpRunning,
        *_WATER_LEVEL,
        MaxRefillTime,
        MaxPhDoses,
        *_UNIT_STATE,
        HeatingControlEnabled,
        FreezeProtectionEnabled,
        *_BACKWASH,
        *_ALARMS,
    ),
    overrides={
        Configuration: "decode_v7_ph_and_oxy",
        AlgaecidePumpRunning: "decode_v7_oxy",
        HeatingControlEnabled: "decode_v7_not_located",
        FreezeProtectionEnabled: "decode_v7_not_located",
    },
    evidence={
        AirTemperature: "unverified: bytes 23-24 = 0xFE70 (no air probe, the SALT marker) in every captured OXY frame, so no entity yet; the Aseko Live app shows air temperature on Oxygen units",
        AlarmNoFlowToProbes: "unconfirmed: byte[13] was 0x00 in every OXY frame; confirmed on NET and HOME only",
        AlarmMaxDisinfectionDose: "unconfirmed: bytes 12-13 were 0x00 in every OXY frame; HOME encoding assumed",
        AlarmPhDosingIneffective: "unconfirmed: bytes 12-13 were 0x00 in every OXY frame; HOME encoding assumed",
        AlarmRapidPhChange: "unconfirmed: byte[13] 0x08 from error_codes.md; never set in the OXY frames",
        AlgaecidePumpRunning: "confirmed: byte[29] 0x10, 2026-04-11 Winnetoux log",
        FreezeProtectionEnabled: "not located: the ASIN AQUA Oxygen manual describes freeze protection; no OXY frame has been compared with it",
        BackwashRunning: "assumed: byte[29] 0x01, confirmed on SALT",
        BackwashDuration: "observed: byte[71] * 10 = 100 s on the Winnetoux OXY (serial 110157165); not compared with the app",
        BackwashInterval: "observed: byte[68] = 0 (disabled) on the Winnetoux OXY (serial 110157165); not compared with the app",
        BackwashStartTime: "observed: bytes 69-70 = 12:30 on the Winnetoux OXY (serial 110157165); not compared with the app",
        Configuration: "confirmed: fixed pH + OXY Pure, the SANOSIL probe sits in the CLF slot",
        DosingDelay: "observed: bytes 106-107 = 120 s on the Winnetoux OXY (serial 110157165); not compared with the app",
        StartupDelay: "observed: bytes 74-75 = 240 s on the Winnetoux OXY; the analysis document mislabels byte[73]",
        FiltrationRunning: "confirmed: byte[29] 0x08 in every captured frame",
        FiltrationSchedule: "observed: byte[37] = 0x03 reads nonstop while the Winnetoux OXY ran filtration 24 h; no schedule transition captured",
        FlocculantPumpRunning: "confirmed: byte[29] 0x20 toggles at the 19:33:52 floc event",
        AlgaecideFlowRate: "confirmed: byte[103] = 60 ml/min (2026-04-11)",
        FlocculantFlowRate: "confirmed: byte[101]",
        OxygenFlowRate: "confirmed: byte[99]",
        PhMinusFlowRate: "confirmed: byte[95] = 60 ml/min (Winnetoux, oxy_device_analysis.md)",
        HeatingRunning: "assumed: byte[29] 0x04 per JS-DE-Tech relay_byte bit 2",
        HeatingControlEnabled: "not located: the ASIN AQUA Oxygen manual describes heating control; no OXY frame has been compared with it",
        MaxRefillTime: "assumed: bytes 76-77 = 3600 s on the Winnetoux OXY, plausible (60 min); verified on SALT only",
        MaxPhDoses: "observed: byte[115] = 30 on the Winnetoux OXY; the position is confirmed on SALT, the OXY setting was never compared",
        OxygenPumpRunning: "confirmed: byte[29] 0x40, 2026-04-11 Winnetoux log",
        Ph: "observed: bytes 14-15 = 7.17 on the Winnetoux OXY (serial 110157165); not compared with the app",
        PhMinusConcentration: "assumed: byte[112], confirmed on HOME",
        PhMinusPumpRunning: "confirmed: byte[29] 0x80, 2026-04-12 Winnetoux log",
        PoolVolume: "observed: bytes 92-93 = 41 m3 on the Winnetoux OXY (serial 110157165); not compared with the app",
        AlgaecideDoseTarget: "confirmed: byte[72] = 15 (2026-04-11)",
        FlocculantDoseTarget: "confirmed: byte[54] = 10 (2026-04-11)",
        OxygenDoseTarget: "confirmed: byte[53] (Winnetoux, 2026-04-11)",
        PhTarget: "observed: byte[52] / 10 = 7.2 on the Winnetoux OXY (serial 110157165); not compared with the app",
        WaterTemperatureTarget: "observed: byte[55] = 25 C on the Winnetoux OXY (serial 110157165); not compared with the app",
        SerialNumber: "confirmed: bytes 0-3, repeated in every segment header",
        ServiceMenuOpen: "observed: byte[37] bit 0x04 clear in every OXY frame; the menu never captured open",
        FiltrationPeriod1Start: "observed: bytes 56-57 = 08:00 in every frame on the Winnetoux OXY (serial 110157165); not compared with the app",
        FiltrationPeriod2Start: "observed: bytes 60-61 = 18:00 in every frame on the Winnetoux OXY (serial 110157165); not compared with the app",
        FiltrationPeriod1End: "observed: bytes 58-59 = 16:00 in every frame on the Winnetoux OXY (serial 110157165); not compared with the app",
        FiltrationPeriod2End: "observed: bytes 62-63 = 22:00 in every frame on the Winnetoux OXY (serial 110157165); not compared with the app",
        Timestamp: "confirmed: bytes 6-11",
        VariableSpeedPumpRunning: "assumed: byte[22] 0x08, confirmed on HOME",
        Refilling: "assumed: byte[29] 0x02, confirmed on HOME",
        WaterFlowToProbes: "observed: byte[28] = 0xAA on the Winnetoux OXY (serial 110157165); not compared with the app",
        WaterLevel: "assumed: byte[27], confirmed on HOME",
        WaterLevelRefillStart: "unconfirmed: byte[103] is algaecide_flow_rate on OXY (confirmed, 60 ml/min); reading it as a level threshold too cannot be right",
        WaterTemperature: "observed: bytes 25-26 = 9.5 C on the Winnetoux OXY (serial 110157165); not compared with the app",
    },
)

# ---------------------------------------------------------------------------
# NET (Aqua NET): measurement and dosing only, no filter, no valve
# ---------------------------------------------------------------------------

NET = Profile(
    name="v7 NET",
    protocol=Protocol.V7,
    model=AsekoDeviceType.NET,
    features=(
        *_IDENTITY,
        *_MEASUREMENTS,
        *_CHLORINE_PROBES,
        PhTarget,
        PoolVolume,
        StartupDelay,
        DosingDelay,
        PhMinusFlowRate,
        *_DISINFECTION_SETPOINTS,
        ChlorineFlowRate,
        ChlorinePumpRunning,
        PhMinusPumpRunning,
        *_ALARMS,
    ),
    overrides={
        ChlorinePumpRunning: "decode_v7_net",
        PhMinusPumpRunning: "decode_v7_net",
    },
    evidence={
        AlarmNoFlowToProbes: "confirmed: byte[13] 0x04 (DomSchCoding, NET frame)",
        AlarmMaxDisinfectionDose: "unconfirmed: byte[12] is 0x00 on NET; HOME encodings assumed",
        AlarmPhDosingIneffective: "unconfirmed: byte[12] is 0x00 on NET; HOME encodings assumed",
        AlarmRapidPhChange: "unconfirmed: byte[13] 0x08 from error_codes.md; never set on NET",
        FreeChlorine: "confirmed: bytes 16-17 / 100",
        FreeChlorineMv: "confirmed: bytes 20-21",
        ChlorinePumpRunning: "confirmed: byte[29] 0x02 (Issue #66)",
        Configuration: "confirmed: byte[4] missing-probe bits (0x09 CLF, 0x0A REDOX, 0x0B DOSE)",
        DosingDelay: "observed: bytes 106-107 on the Issue #66 NET; not compared with the app",
        StartupDelay: "unverified: bytes 74-75 = 0xFFFF (not filled in) on the Issue #66 NET frame and on the ChemDoserProxy NET frame",
        ChlorineFlowRate: "confirmed: byte[99] (net_device_analysis.md)",
        PhMinusFlowRate: "confirmed: byte[95] (Issue #110, #115)",
        Ph: "confirmed: bytes 14-15 / 100 (Issue #66 frames)",
        PhMinusPumpRunning: "confirmed: byte[29] 0x01 (Issue #66)",
        PoolVolume: "observed: bytes 92-93 on the Issue #66 NET; not compared with the app",
        ChlorineDoseTarget: "observed: byte[53] = 5 ml/m3/h in DOSE mode (2026-04-07 capture); not compared with the app",
        FreeChlorineTarget: "observed: byte[53] / 10 on the Issue #66 NET; not compared with the app",
        PhTarget: "confirmed: byte[52] / 10 (Issue #66 frames)",
        RedoxTarget: "unverified: byte[53] * 10 on a REDOX NET; no such frame captured",
        SerialNumber: "confirmed: bytes 0-3, repeated in every segment header",
        Timestamp: "n/a: bytes 6-11 are 0xFF on every NET frame, Home Assistant's clock is used instead",
        WaterFlowToProbes: "confirmed: byte[28] == 0xAA (Issue #66 frames)",
        WaterTemperature: "confirmed: bytes 25-26 / 10 (Issue #66 frames)",
    },
)

# ---------------------------------------------------------------------------
# PROFI: unit type 0x10, unconfirmed
# ---------------------------------------------------------------------------

PROFI = Profile(
    name="v7 PROFI",
    protocol=Protocol.V7,
    model=AsekoDeviceType.PROFI,
    features=(
        *_IDENTITY,
        *_MEASUREMENTS,
        *_CHLORINE_PROBES,
        *_SETTINGS,
        FreeChlorineTarget,
        ChlorineDoseTarget,
        FlocculantDoseTarget,
        ChlorineFlowRate,
        FlocculantFlowRate,
        *_FILTRATION,
        ServiceMenuOpen,
        ChlorinePumpRunning,
        PhMinusPumpRunning,
        FlocculantPumpRunning,
        *_WATER_LEVEL,
        MaxRefillTime,
        HeatingRunning,
        PhMinusConcentration,
        MaxPhDoses,
        *_BACKWASH,
        *_ALARMS,
    ),
    overrides={
        Configuration: "decode_v7_without_dose",
        FlocculantDoseTarget: "decode_v7_routed_by_byte37",
        FlocculantFlowRate: "decode_v7_routed_by_byte37",
    },
    evidence={
        AlarmNoFlowToProbes: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        AlarmMaxDisinfectionDose: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        AlarmPhDosingIneffective: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        AlarmRapidPhChange: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        BackwashRunning: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        BackwashDuration: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        BackwashInterval: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        BackwashStartTime: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FreeChlorine: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FreeChlorineMv: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        ChlorinePumpRunning: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        Configuration: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        DosingDelay: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        StartupDelay: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FiltrationRunning: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FiltrationSchedule: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FlocculantPumpRunning: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        ChlorineFlowRate: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FlocculantFlowRate: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        PhMinusFlowRate: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        HeatingRunning: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        Ph: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        MaxRefillTime: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md); the 2021 PROFI manual lists a max. filling time",
        MaxPhDoses: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        PhMinusConcentration: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        PhMinusPumpRunning: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        PoolVolume: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        Redox: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        ChlorineDoseTarget: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FlocculantDoseTarget: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md); the PROFI setpoints screen has a flocculant dose (ml/24 h m3) on its shared flocculant / algicide output",
        FreeChlorineTarget: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        PhTarget: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        WaterTemperatureTarget: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        SerialNumber: "confirmed: bytes 0-3, repeated in every segment header",
        ServiceMenuOpen: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FiltrationPeriod1Start: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FiltrationPeriod2Start: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FiltrationPeriod1End: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FiltrationPeriod2End: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        Timestamp: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        Refilling: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        WaterFlowToProbes: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        WaterLevel: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        WaterLevelRefillStop: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        WaterLevelRefillStart: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        WaterLevelHighAlarm: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        WaterLevelLowAlarm: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        WaterTemperature: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
    },
)

# ---------------------------------------------------------------------------
# A unit type nobody has mapped.  Read everything that has a generic v7
# reading -- every probe, the shared-port layout most models use, the
# default actuator bits -- so that the diagnostics of such a unit show as
# much as the frame can be made to say.  Nothing here is verified for the
# unit at hand: the coordinator keeps it out of the entity platforms and
# reports it separately in diagnostics as unrecognised.
#
# Left out are readings whose bytes mean something else on other models and
# so cannot be called generic: SALT's electrolyser and salinity (bytes 20-21
# are free_chlorine_mv elsewhere), the OXY dose and pump (byte[53] and bit 0x40
# are chlorine elsewhere) and HOME's heating / antifreeze enables (byte[37]
# 0x80 is the algicide routing elsewhere).  Air temperature is left out too:
# NET carries unrelated data in bytes 23-24.
# ---------------------------------------------------------------------------

_UNKNOWN_FEATURES = (
    *_IDENTITY,
    *_MEASUREMENTS,
    *_CHLORINE_PROBES,
    *_SETTINGS,
    *_DISINFECTION_SETPOINTS,
    AlgaecideDoseTarget,
    FlocculantDoseTarget,
    ChlorineFlowRate,
    AlgaecideFlowRate,
    FlocculantFlowRate,
    *_FILTRATION,
    ServiceMenuOpen,
    ChlorinePumpRunning,
    PhMinusPumpRunning,
    AlgaecidePumpRunning,
    FlocculantPumpRunning,
    *_WATER_LEVEL,
    MaxRefillTime,
    MaxPhDoses,
    *_UNIT_STATE,
    *_BACKWASH,
    *_ALARMS,
)

UNKNOWN = Profile(
    name="v7 unknown unit type",
    protocol=Protocol.V7,
    model=None,
    features=_UNKNOWN_FEATURES,
    overrides={
        Configuration: "decode_v7_all_probes",
        **_SHARED_THIRD_PUMP,
    },
    evidence={
        AlarmNoFlowToProbes: "unverified: unmapped unit type, read with the generic v7 reading",
        AlarmMaxDisinfectionDose: "unverified: unmapped unit type, read with the generic v7 reading",
        AlarmPhDosingIneffective: "unverified: unmapped unit type, read with the generic v7 reading",
        AlarmRapidPhChange: "unverified: unmapped unit type, read with the generic v7 reading",
        AlgaecidePumpRunning: "unverified: unmapped unit type, read with the generic v7 reading",
        BackwashRunning: "unverified: unmapped unit type, read with the generic v7 reading",
        BackwashDuration: "unverified: unmapped unit type, read with the generic v7 reading",
        BackwashInterval: "unverified: unmapped unit type, read with the generic v7 reading",
        BackwashStartTime: "unverified: unmapped unit type, read with the generic v7 reading",
        FreeChlorine: "unverified: unmapped unit type, read with the generic v7 reading",
        FreeChlorineMv: "unverified: unmapped unit type, read with the generic v7 reading",
        ChlorinePumpRunning: "unverified: unmapped unit type, read with the generic v7 reading",
        Configuration: "unverified: unmapped unit type, read with the generic v7 reading",
        DosingDelay: "unverified: unmapped unit type, read with the generic v7 reading",
        StartupDelay: "unverified: unmapped unit type, read with the generic v7 reading",
        FiltrationRunning: "unverified: unmapped unit type, read with the generic v7 reading",
        FiltrationSchedule: "unverified: unmapped unit type, read with the generic v7 reading",
        FlocculantPumpRunning: "unverified: unmapped unit type, read with the generic v7 reading",
        AlgaecideFlowRate: "unverified: unmapped unit type, read with the generic v7 reading",
        ChlorineFlowRate: "unverified: unmapped unit type, read with the generic v7 reading",
        FlocculantFlowRate: "unverified: unmapped unit type, read with the generic v7 reading",
        PhMinusFlowRate: "unverified: unmapped unit type, read with the generic v7 reading",
        HeatingRunning: "unverified: unmapped unit type, read with the generic v7 reading",
        MaxRefillTime: "unverified: unmapped unit type, read with the generic v7 reading",
        Ph: "unverified: unmapped unit type, read with the generic v7 reading",
        PhMinusConcentration: "unverified: unmapped unit type, read with the generic v7 reading",
        PhMinusPumpRunning: "unverified: unmapped unit type, read with the generic v7 reading",
        PoolVolume: "unverified: unmapped unit type, read with the generic v7 reading",
        Redox: "unverified: unmapped unit type, read with the generic v7 reading",
        AlgaecideDoseTarget: "unverified: unmapped unit type, read with the generic v7 reading",
        ChlorineDoseTarget: "unverified: unmapped unit type, read with the generic v7 reading",
        FreeChlorineTarget: "unverified: unmapped unit type, read with the generic v7 reading",
        FlocculantDoseTarget: "unverified: unmapped unit type, read with the generic v7 reading",
        PhTarget: "unverified: unmapped unit type, read with the generic v7 reading",
        RedoxTarget: "unverified: unmapped unit type, read with the generic v7 reading",
        WaterTemperatureTarget: "unverified: unmapped unit type, read with the generic v7 reading",
        SerialNumber: "unverified: unmapped unit type, read with the generic v7 reading",
        ServiceMenuOpen: "unverified: unmapped unit type, read with the generic v7 reading",
        FiltrationPeriod1Start: "unverified: unmapped unit type, read with the generic v7 reading",
        FiltrationPeriod2Start: "unverified: unmapped unit type, read with the generic v7 reading",
        FiltrationPeriod1End: "unverified: unmapped unit type, read with the generic v7 reading",
        FiltrationPeriod2End: "unverified: unmapped unit type, read with the generic v7 reading",
        Timestamp: "unverified: unmapped unit type, read with the generic v7 reading",
        VariableSpeedPumpRunning: "unverified: unmapped unit type, read with the generic v7 reading",
        Refilling: "unverified: unmapped unit type, read with the generic v7 reading",
        WaterFlowToProbes: "unverified: unmapped unit type, read with the generic v7 reading",
        WaterLevel: "unverified: unmapped unit type, read with the generic v7 reading",
        WaterLevelRefillStop: "unverified: unmapped unit type, read with the generic v7 reading",
        WaterLevelRefillStart: "unverified: unmapped unit type, read with the generic v7 reading",
        WaterLevelHighAlarm: "unverified: unmapped unit type, read with the generic v7 reading",
        WaterLevelLowAlarm: "unverified: unmapped unit type, read with the generic v7 reading",
        WaterTemperature: "unverified: unmapped unit type, read with the generic v7 reading",
    },
)

BY_MODEL: dict[AsekoDeviceType | None, Profile] = {
    AsekoDeviceType.SALT: SALT,
    AsekoDeviceType.OXY: OXY,
    AsekoDeviceType.NET: NET,
    AsekoDeviceType.PROFI: PROFI,
    None: UNKNOWN,
}
