"""v7 profiles: the 120-byte binary protocol, firmware up to 7.x, port 47524.

One profile per model, two for HOME because its firmware revisions encode
byte[37] differently.  A feature listed here is one the model has; a
feature missing from a profile is one it does not have, and its field stays
None so no entity is created for it.  ``overrides`` name the reading to use
where this model's frame differs from the protocol default; everything else
uses the default reading from the feature's own file.

``evidence`` records why each entry is believed, in the words of the
captures, issues and the documents in docs/device analyzes/ that
established it.  "confirmed" means checked against the unit's display or the
Aseko Live app; "observed" means seen in real frames with plausible values but
not compared; "uncertain", "assumed" and "unverified" mean the earlier decoder
read it that way and nothing has contradicted it yet.  Every profile spells
its evidence out in full so that nothing is inherited from another model.
The support matrix in the docs is generated from these dictionaries.
"""

from __future__ import annotations

from ...aseko_data import AsekoDeviceType, AsekoFirmwareVariant, AsekoProfileFlag
from ..decoders import (
    AirTemperature,
    AlarmNoFlowToProbes,
    AlarmOrpTooManyDoses,
    AlarmPhTooManyDoses,
    AlarmRapidPhChange,
    AlgicidePumpRunning,
    AntifreezeEnabled,
    BackwashActive,
    BackwashDuration,
    BackwashEveryNDays,
    BackwashTime,
    ClFree,
    ClFreeMv,
    ClPumpRunning,
    Configuration,
    DelayAfterDose,
    DelayAfterStartup,
    ElectrolyzerActive,
    ElectrolyzerDirection,
    ElectrolyzerPower,
    FiltrationPumpRunning,
    FiltrationSchedule,
    FiltrationStart1,
    FiltrationStart2,
    FiltrationStop1,
    FiltrationStop2,
    FlocPumpRunning,
    FlowrateAlgicide,
    FlowrateChlor,
    FlowrateFloc,
    FlowrateOxy,
    FlowratePhMinus,
    HeatingActive,
    HeatingControlEnabled,
    MaxFillingTime,
    OxyPumpRunning,
    Ph,
    PhMinusConcentration,
    PhMinusPumpRunning,
    PoolVolume,
    Redox,
    RequiredAlgicide,
    RequiredClDose,
    RequiredClFree,
    RequiredFloc,
    RequiredOxyDose,
    RequiredPh,
    RequiredRedox,
    RequiredWaterTemperature,
    Salinity,
    SerialNumber,
    ServiceMenuOpen,
    Timestamp,
    VspPumpRunning,
    WaterFillingActive,
    WaterFlowToProbes,
    WaterLevel,
    WaterLevelFillingOff,
    WaterLevelFillingOn,
    WaterLevelHighAlarm,
    WaterLevelLowAlarm,
    WaterTemperature,
)
from ..frame import Protocol
from ..profile import Profile

# ---------------------------------------------------------------------------
# Feature groups shared between profiles.  A group is a convenience for
# reading the lists below, not a concept the decoder knows.
# ---------------------------------------------------------------------------

_IDENTITY = (SerialNumber, Configuration, Timestamp)
_MEASUREMENTS = (WaterTemperature, WaterFlowToProbes)
_CHLORINE_PROBES = (Ph, Redox, ClFree, ClFreeMv)
_SETTINGS = (
    RequiredPh,
    RequiredWaterTemperature,
    PoolVolume,
    DelayAfterStartup,
    DelayAfterDose,
    FlowratePhMinus,
)
_ALARMS = (
    AlarmPhTooManyDoses,
    AlarmOrpTooManyDoses,
    AlarmNoFlowToProbes,
    AlarmRapidPhChange,
)
_FILTRATION = (
    FiltrationStart1,
    FiltrationStop1,
    FiltrationStart2,
    FiltrationStop2,
    FiltrationSchedule,
    FiltrationPumpRunning,
)
_BACKWASH = (BackwashEveryNDays, BackwashTime, BackwashDuration, BackwashActive)
_WATER_LEVEL = (
    WaterLevel,
    WaterLevelLowAlarm,
    WaterLevelFillingOn,
    WaterLevelFillingOff,
    WaterLevelHighAlarm,
    WaterFillingActive,
)
_UNIT_STATE = (HeatingActive, VspPumpRunning, PhMinusConcentration)

# The disinfection setpoint family on chlorine units: byte[53] is one of
# these three depending on the installed probes, each answers only when it
# is the one that applies.
_DISINFECTION_SETPOINTS = (RequiredClFree, RequiredRedox, RequiredClDose)

# Algicide / flocculant on a single shared port, routed by byte[37] bit 0x80.
_SHARED_THIRD_PUMP = {
    RequiredAlgicide: "decode_v7_routed_by_byte37",
    RequiredFloc: "decode_v7_routed_by_byte37",
    FlowrateAlgicide: "decode_v7_routed_by_byte37",
    FlowrateFloc: "decode_v7_routed_by_byte37",
}

# ---------------------------------------------------------------------------
# SALT
# ---------------------------------------------------------------------------

SALT = Profile(
    name="v7 SALT",
    protocol=Protocol.V7,
    model=AsekoDeviceType.SALT,
    features=(
        *_IDENTITY,
        *_MEASUREMENTS,
        AirTemperature,
        *_CHLORINE_PROBES,
        Salinity,
        ElectrolyzerPower,
        ElectrolyzerActive,
        ElectrolyzerDirection,
        *_SETTINGS,
        *_DISINFECTION_SETPOINTS,
        RequiredAlgicide,
        RequiredFloc,
        FlowrateChlor,
        FlowrateAlgicide,
        FlowrateFloc,
        *_FILTRATION,
        ServiceMenuOpen,
        PhMinusPumpRunning,
        AlgicidePumpRunning,
        FlocPumpRunning,
        *_WATER_LEVEL,
        MaxFillingTime,
        *_UNIT_STATE,
        *_BACKWASH,
        *_ALARMS,
    ),
    overrides=_SHARED_THIRD_PUMP,
    flags=frozenset({AsekoProfileFlag.MENU_BIT_IS_PRESENCE_ONLY}),
    evidence={
        AirTemperature: "confirmed: serial 110194590, two dumps vs unit display (Issue #155)",
        AlarmNoFlowToProbes: "confirmed: byte[13] 0x04 (DomSchCoding, NET frame)",
        AlarmOrpTooManyDoses: "confirmed on HOME: byte[12] 0x20 (Issue #134), byte[13] 0x01 (Issue #151)",
        AlarmPhTooManyDoses: "confirmed on HOME: byte[12] 0x40 (Issue #134); byte[13] 0x02 inferred",
        AlarmRapidPhChange: "unconfirmed: byte[13] 0x08 from error_codes.md; never set in the own SALT dumps, 37 frames 2026-08-08..28",
        AlgicidePumpRunning: "confirmed: byte[29] 0x20, 27 frames (PR #87)",
        BackwashActive: "confirmed: byte[29] 0x01, 2026-08-11 capture of a manual backwash",
        BackwashDuration: "confirmed: byte[71] * 10 matched the relay window",
        BackwashEveryNDays: "confirmed: byte[68] vs the unit's backwash settings (own SALT, the v1.8.0 backwash tracker classifies cycles against it)",
        BackwashTime: "confirmed: bytes 69-70 vs the unit's backwash settings (own SALT, v1.8.0 backwash tracker)",
        ClFree: "confirmed: bytes 16-17 = 0.77 and 0.93 mg/l on the CLF unit (serial 110194590) of the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer",
        ClFreeMv: "confirmed: bytes 20-21 = 6656 and 6934 mV on the CLF unit of the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer",
        Configuration: "confirmed: byte[4] missing-probe bits (0x0D CLF, 0x0E REDOX, 0x0F DOSE)",
        DelayAfterDose: "confirmed: bytes 106-107",
        DelayAfterStartup: "confirmed: bytes 74-75",
        ElectrolyzerActive: "confirmed: byte[29] 0x10, 25 frames (PR #87)",
        ElectrolyzerDirection: "confirmed: left, right and waiting all seen (own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer)",
        ElectrolyzerPower: "confirmed: byte[21] while 0x10 set (PR #87)",
        FiltrationPumpRunning: "confirmed: byte[29] 0x08 in every active phase (PR #87)",
        FiltrationSchedule: "confirmed: 0xC3 / 0xD3 / 0xF3, every transition both ways",
        FlocPumpRunning: "confirmed: byte[29] 0x20, Apr 3 frames",
        FlowrateAlgicide: "confirmed: byte[101] via byte[37] 0x80 (Issue #84, SALT v5.0, shows 0x13 with bit 7 clear while set to algicide: an older firmware may route differently)",
        FlowrateChlor: "unverified: byte[99]; 0xFF in every frame of the own SALT dumps, 37 frames 2026-08-08..28 (no chlorine pump on a SALT)",
        FlowrateFloc: "confirmed: byte[101] via byte[37] 0x80 clear (Issue #84, SALT v5.0, shows 0x13 with bit 7 clear while set to algicide: an older firmware may route differently)",
        FlowratePhMinus: "confirmed: byte[95] (Issue #110, #115)",
        HeatingActive: "assumed: byte[29] 0x04 per JS-DE-Tech relay_byte bit 2; never set in the own SALT dumps, 37 frames 2026-08-08..28",
        MaxFillingTime: "confirmed: bytes 76-77 vs Aseko Live (1800 s = 30 min)",
        Ph: "confirmed: bytes 14-15 / 100 on every model",
        PhMinusConcentration: "confirmed: byte[112] = 14 then 15 % in the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer",
        PhMinusPumpRunning: "unconfirmed: byte[29] 0x80; the bit was never set in the own SALT dumps, 37 frames 2026-08-08..28",
        PoolVolume: "confirmed: bytes 92-93",
        Redox: "confirmed: bytes 16-19 = 593..670 mV on the REDOX unit of the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer",
        RequiredAlgicide: "confirmed: byte[54] via byte[37] 0x80 (@hopkins-tk, Issue #84) (Issue #84, SALT v5.0, shows 0x13 with bit 7 clear while set to algicide: an older firmware may route differently)",
        RequiredClDose: "unverified: byte[53] for a DOSE unit; neither unit of the own SALT dumps, 37 frames 2026-08-08..28 is one",
        RequiredClFree: "confirmed: byte[53] / 10 = 0.9 mg/l on the CLF unit of the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer",
        RequiredFloc: "confirmed: byte[54] via byte[37] 0x80 clear (Issue #84, SALT v5.0, shows 0x13 with bit 7 clear while set to algicide: an older firmware may route differently)",
        RequiredPh: "confirmed: byte[52] / 10 on every model",
        RequiredRedox: "confirmed: byte[53] * 10 = 670 mV on the REDOX unit of the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer",
        RequiredWaterTemperature: "confirmed: byte[55] = 25 C in every frame of the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer",
        Salinity: "confirmed: byte[20] / 10",
        SerialNumber: "confirmed: bytes 0-3, repeated in every segment header",
        ServiceMenuOpen: "confirmed: 0xD7 / 0xF7 then the unit goes offline",
        FiltrationStart1: "confirmed: bytes 56-57 changed 08:00 -> 09:00 with the timer settings during the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer",
        FiltrationStart2: "confirmed: bytes 60-61 changed 18:00 -> 18:10 with the timer settings during the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer",
        FiltrationStop1: "confirmed: bytes 58-59 changed 18:05 / 19:00 / 21:35 with the timer settings during the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer",
        FiltrationStop2: "confirmed: bytes 62-63 changed 22:00 -> 23:55 with the timer settings during the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer",
        Timestamp: "confirmed: bytes 6-11",
        VspPumpRunning: "confirmed: byte[22] toggles 0x10 / 0x18 across the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer",
        WaterFillingActive: "assumed: byte[29] 0x02, confirmed on HOME only; never set in the own SALT dumps, 37 frames 2026-08-08..28",
        WaterFlowToProbes: "confirmed: byte[28] == 0xAA",
        WaterLevel: "confirmed: byte[27] 14..25 cm across the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer",
        WaterLevelFillingOff: "confirmed: byte[104] = 25 and 35 cm on the two units of the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer",
        WaterLevelFillingOn: "confirmed: byte[103] = 10 and 33 cm on the two units of the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer",
        WaterLevelHighAlarm: "confirmed: byte[105] = 40 and 56..73 cm on the two units of the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer",
        WaterLevelLowAlarm: "confirmed: byte[102] = 5 and 31 cm on the two units of the own SALT dumps, 37 frames 2026-08-08..28, checked against the unit by the maintainer; thresholds ordered low < on < off < high",
        WaterTemperature: "confirmed: bytes 25-26 / 10 on every model",
    },
)

# ---------------------------------------------------------------------------
# HOME, two firmware revisions
# ---------------------------------------------------------------------------

_HOME_FEATURES = (
    *_IDENTITY,
    *_MEASUREMENTS,
    *_CHLORINE_PROBES,
    *_SETTINGS,
    *_DISINFECTION_SETPOINTS,
    RequiredAlgicide,
    RequiredFloc,
    FlowrateChlor,
    FlowrateAlgicide,
    FlowrateFloc,
    *_FILTRATION,
    ClPumpRunning,
    PhMinusPumpRunning,
    AlgicidePumpRunning,
    FlocPumpRunning,
    *_WATER_LEVEL,
    MaxFillingTime,
    *_UNIT_STATE,
    HeatingControlEnabled,
    AntifreezeEnabled,
    *_BACKWASH,
    *_ALARMS,
)

HOME_A = Profile(
    name="v7 HOME firmware A",
    protocol=Protocol.V7,
    model=AsekoDeviceType.HOME,
    firmware=AsekoFirmwareVariant.HOME_A,
    features=_HOME_FEATURES,
    overrides={
        Configuration: "decode_v7_by_unit_type_byte",
        FiltrationSchedule: "decode_v7_home_a",
    },
    evidence={
        AlarmNoFlowToProbes: "confirmed: byte[13] 0x04 (DomSchCoding, NET frame)",
        AlarmOrpTooManyDoses: "confirmed on HOME: byte[12] 0x20 (Issue #134), byte[13] 0x01 (Issue #151)",
        AlarmPhTooManyDoses: "confirmed on HOME: byte[12] 0x40 (Issue #134); byte[13] 0x02 inferred",
        AlarmRapidPhChange: "unconfirmed: byte[13] 0x08 was set on serial 110128063 with no matching alarm known in the app",
        AlgicidePumpRunning: "uncertain: byte[29] 0x20 assumed",
        AntifreezeEnabled: "confirmed: byte[37] 0x80, serial 110175608 (Issue #136)",
        BackwashActive: "assumed: byte[29] 0x01, confirmed on SALT",
        BackwashDuration: "confirmed: byte[71] * 10 = 120 s vs '02:00 min' in Aseko Live, serial 110128063",
        BackwashEveryNDays: "confirmed: byte[68] = 3 vs 'every 3 days' in Aseko Live, serial 110128063",
        BackwashTime: "confirmed: bytes 69-70 = 21:00 vs Aseko Live, serial 110128063",
        ClFree: "confirmed: bytes 16-17 = 0.00 mg/l vs Aseko Live, serial 110128063 (2026-04-28)",
        ClFreeMv: "confirmed: bytes 20-21 = 2 mV, serial 110128063 (2026-04-28)",
        ClPumpRunning: "uncertain: byte[29] 0x40, port may be chlorine or OXY Pure",
        Configuration: "confirmed: byte[4] exact sub-type, 0x02 CLF / 0x03 REDOX (Issue #110)",
        DelayAfterDose: "confirmed: bytes 106-107 = 240 s vs '4 min' in Aseko Live, serial 110128063",
        DelayAfterStartup: "confirmed: bytes 74-75 = 480 s vs '8 min' in Aseko Live, serial 110128063",
        FiltrationPumpRunning: "observed: byte[29] 0x08 clear while Aseko Live showed STOP, serial 110128063; the set state was not captured on firmware A",
        FiltrationSchedule: "confirmed: 0x43 nonstop / 0x53 timer, serial 110128063; fallback for 0x41 / 0x45 / 0x49 (Issue #135)",
        FlocPumpRunning: "uncertain: byte[29] 0x20 assumed",
        FlowrateAlgicide: "confirmed: byte[103], Issues #110, #115 -- but the same byte is also read as water_level_filling_on, and one of the two must be wrong",
        FlowrateChlor: "confirmed: byte[99], serials 110071590 / 110128063 (Issues #110, #115)",
        FlowrateFloc: "confirmed: byte[101], Issues #110, #115",
        FlowratePhMinus: "confirmed: byte[95] = 60, Aseko Live lists the pH- pump, serial 110128063",
        HeatingActive: "assumed: byte[29] 0x04 per JS-DE-Tech relay_byte bit 2; no HOME frame with the heater running (open item 9)",
        HeatingControlEnabled: "confirmed: byte[37] 0x08, serial 110175608 (Issue #135)",
        MaxFillingTime: "assumed: bytes 76-77 = 10800 s on serial 110128063, plausible (180 min); verified on SALT only",
        Ph: "confirmed: bytes 14-15 = 6.29 vs 6.56 in Aseko Live (later reading), serial 110128063",
        PhMinusConcentration: "confirmed: byte[112], serial 110175608 (Issue #139)",
        PhMinusPumpRunning: "uncertain: byte[29] 0x80 assumed",
        PoolVolume: "confirmed: bytes 92-93 = 60 m3 vs Aseko Live, serial 110128063",
        RequiredAlgicide: "confirmed: byte[72], serial 110128063 (2026-04-28)",
        RequiredClFree: "confirmed: byte[53] / 10 = 0.3 mg/l vs Aseko Live, serial 110128063",
        RequiredFloc: "confirmed: byte[54], serial 110128063 (2026-04-28)",
        RequiredPh: "confirmed: byte[52] / 10 = 7.0 vs Aseko Live, serial 110128063",
        RequiredWaterTemperature: "confirmed: byte[55] is the heating setpoint on serial 110175608 (Issue #135); 25 C with heating disabled on 110128063",
        SerialNumber: "confirmed: bytes 0-3, repeated in every segment header",
        FiltrationStart1: "confirmed: bytes 56-57 = 08:00 last-configured, serial 110128063 (Issues #110, #133)",
        FiltrationStart2: "confirmed: bytes 60-61 = 18:00 last-configured, serial 110128063 (Issues #110, #133)",
        FiltrationStop1: "confirmed: bytes 58-59 = 16:00 last-configured, serial 110128063 (Issues #110, #133)",
        FiltrationStop2: "confirmed: bytes 62-63 = 22:00 last-configured, serial 110128063 (Issues #110, #133)",
        Timestamp: "confirmed: bytes 6-11",
        VspPumpRunning: "confirmed: byte[22] 0x08, serial 110175608",
        WaterFillingActive: "confirmed: byte[29] 0x02 (DomSchCoding #100)",
        WaterFlowToProbes: "confirmed: byte[28] != 0xAA while Aseko Live showed 'NO', serial 110128063",
        WaterLevel: "confirmed: byte[27] (domin211, Issue #110)",
        WaterLevelFillingOff: "confirmed: byte[104] (domin211, DomSchCoding, Issue #110)",
        WaterLevelFillingOn: "unconfirmed: byte[103] = 33 on serial 110128063 is read both as this threshold (cm) and as flowrate_algicide (ml/min); the two mappings cannot both be right",
        WaterLevelHighAlarm: "confirmed: byte[105] (domin211, Issue #110)",
        WaterLevelLowAlarm: "confirmed: byte[102] (domin211, Issue #110)",
        WaterTemperature: "confirmed: bytes 25-26 = 37.9 C vs 38.2 C in Aseko Live (later reading), serial 110128063",
    },
)

HOME_B = Profile(
    name="v7 HOME firmware B",
    protocol=Protocol.V7,
    model=AsekoDeviceType.HOME,
    firmware=AsekoFirmwareVariant.HOME_B,
    features=(*_HOME_FEATURES, ServiceMenuOpen),
    overrides={
        Configuration: "decode_v7_by_unit_type_byte",
        FiltrationPumpRunning: "decode_v7_menu_override",
    },
    evidence={
        AlarmNoFlowToProbes: "confirmed: byte[13] 0x04 (DomSchCoding, NET frame)",
        AlarmOrpTooManyDoses: "confirmed on HOME: byte[12] 0x20 (Issue #134), byte[13] 0x01 (Issue #151)",
        AlarmPhTooManyDoses: "confirmed on HOME: byte[12] 0x40 (Issue #134); byte[13] 0x02 inferred",
        AlarmRapidPhChange: "unconfirmed: byte[13] 0x08 was set on serial 110128063 with no matching alarm known in the app",
        AlgicidePumpRunning: "uncertain: byte[29] 0x20 assumed",
        AntifreezeEnabled: "unverified: byte[37] 0x80 read as on firmware A, no capture on B",
        BackwashActive: "assumed: byte[29] 0x01, confirmed on SALT",
        BackwashDuration: "confirmed: byte[71] * 10 = 120 s vs '02:00 min' in Aseko Live, serial 110128063",
        BackwashEveryNDays: "confirmed: byte[68] = 3 vs 'every 3 days' in Aseko Live, serial 110128063",
        BackwashTime: "confirmed: bytes 69-70 = 21:00 vs Aseko Live, serial 110128063",
        ClFree: "confirmed: bytes 16-17 = 0.00 mg/l vs Aseko Live, serial 110128063 (2026-04-28)",
        ClFreeMv: "confirmed: bytes 20-21 = 2 mV, serial 110128063 (2026-04-28)",
        ClPumpRunning: "uncertain: byte[29] 0x40, port may be chlorine or OXY Pure",
        Configuration: "confirmed: byte[4] exact sub-type, 0x02 CLF / 0x03 REDOX (Issue #110)",
        DelayAfterDose: "confirmed: bytes 106-107 = 240 s vs '4 min' in Aseko Live, serial 110128063",
        DelayAfterStartup: "confirmed: bytes 74-75 = 480 s vs '8 min' in Aseko Live, serial 110128063",
        FiltrationPumpRunning: "confirmed: byte[29] 0x08 stays set under the override, so 0x04 wins (Issue #133)",
        FiltrationSchedule: "confirmed: 0x01 / 0x11 / 0x31, serial 110169464 (Issue #133)",
        FlocPumpRunning: "uncertain: byte[29] 0x20 assumed",
        FlowrateAlgicide: "confirmed: byte[103], Issues #110, #115 -- but the same byte is also read as water_level_filling_on, and one of the two must be wrong",
        FlowrateChlor: "confirmed: byte[99], serials 110071590 / 110128063 (Issues #110, #115)",
        FlowrateFloc: "confirmed: byte[101], Issues #110, #115",
        FlowratePhMinus: "confirmed: byte[95] = 60, Aseko Live lists the pH- pump, serial 110128063",
        HeatingActive: "assumed: byte[29] 0x04 per JS-DE-Tech relay_byte bit 2; no HOME frame with the heater running (open item 9)",
        HeatingControlEnabled: "unverified: byte[37] 0x08 read as on firmware A, no capture on B",
        MaxFillingTime: "assumed: bytes 76-77 = 10800 s on serial 110128063, plausible (180 min); verified on SALT only",
        Ph: "confirmed: bytes 14-15 = 6.29 vs 6.56 in Aseko Live (later reading), serial 110128063",
        PhMinusConcentration: "confirmed: byte[112], serial 110175608 (Issue #139)",
        PhMinusPumpRunning: "uncertain: byte[29] 0x80 assumed",
        PoolVolume: "confirmed: bytes 92-93 = 60 m3 vs Aseko Live, serial 110128063",
        RequiredAlgicide: "confirmed: byte[72], serial 110128063 (2026-04-28)",
        RequiredClFree: "confirmed: byte[53] / 10 = 0.3 mg/l vs Aseko Live, serial 110128063",
        RequiredFloc: "confirmed: byte[54], serial 110128063 (2026-04-28)",
        RequiredPh: "confirmed: byte[52] / 10 = 7.0 vs Aseko Live, serial 110128063",
        RequiredWaterTemperature: "confirmed: byte[55] is the heating setpoint on serial 110175608 (Issue #135); 25 C with heating disabled on 110128063",
        SerialNumber: "confirmed: bytes 0-3, repeated in every segment header",
        ServiceMenuOpen: "confirmed: byte[37] 0x04 as a standing pump override (Issue #133)",
        FiltrationStart1: "confirmed: bytes 56-57 = 08:00 last-configured, serial 110128063 (Issues #110, #133)",
        FiltrationStart2: "confirmed: bytes 60-61 = 18:00 last-configured, serial 110128063 (Issues #110, #133)",
        FiltrationStop1: "confirmed: bytes 58-59 = 16:00 last-configured, serial 110128063 (Issues #110, #133)",
        FiltrationStop2: "confirmed: bytes 62-63 = 22:00 last-configured, serial 110128063 (Issues #110, #133)",
        Timestamp: "confirmed: bytes 6-11",
        VspPumpRunning: "confirmed: byte[22] 0x08, serial 110175608",
        WaterFillingActive: "confirmed: byte[29] 0x02 (DomSchCoding #100)",
        WaterFlowToProbes: "confirmed: byte[28] != 0xAA while Aseko Live showed 'NO', serial 110128063",
        WaterLevel: "confirmed: byte[27] (domin211, Issue #110)",
        WaterLevelFillingOff: "confirmed: byte[104] (domin211, DomSchCoding, Issue #110)",
        WaterLevelFillingOn: "unconfirmed: byte[103] = 33 on serial 110128063 is read both as this threshold (cm) and as flowrate_algicide (ml/min); the two mappings cannot both be right",
        WaterLevelHighAlarm: "confirmed: byte[105] (domin211, Issue #110)",
        WaterLevelLowAlarm: "confirmed: byte[102] (domin211, Issue #110)",
        WaterTemperature: "confirmed: bytes 25-26 = 37.9 C vs 38.2 C in Aseko Live (later reading), serial 110128063",
    },
)

# A HOME frame with byte[37] unset says nothing about its firmware.  Read
# what both revisions share and nothing that only one of them has, so that no
# entity is created on the strength of a guess: service_menu_open exists only
# on firmware B and is left out.  Every byte[37] reading returns "unknown"
# on such a frame anyway, so the values cannot differ from either revision.
HOME_UNKNOWN_FIRMWARE = Profile(
    name="v7 HOME firmware not yet known",
    protocol=Protocol.V7,
    model=AsekoDeviceType.HOME,
    features=_HOME_FEATURES,
    overrides={Configuration: "decode_v7_by_unit_type_byte"},
    evidence={
        AlarmNoFlowToProbes: "confirmed: byte[13] 0x04 (DomSchCoding, NET frame)",
        AlarmOrpTooManyDoses: "confirmed on HOME: byte[12] 0x20 (Issue #134), byte[13] 0x01 (Issue #151)",
        AlarmPhTooManyDoses: "confirmed on HOME: byte[12] 0x40 (Issue #134); byte[13] 0x02 inferred",
        AlarmRapidPhChange: "unconfirmed: byte[13] 0x08 was set on serial 110128063 with no matching alarm known in the app",
        AlgicidePumpRunning: "uncertain: byte[29] 0x20 assumed",
        AntifreezeEnabled: "n/a: byte[37] is unset on every frame decoded with this profile",
        BackwashActive: "assumed: byte[29] 0x01, confirmed on SALT",
        BackwashDuration: "confirmed: byte[71] * 10 = 120 s vs '02:00 min' in Aseko Live, serial 110128063",
        BackwashEveryNDays: "confirmed: byte[68] = 3 vs 'every 3 days' in Aseko Live, serial 110128063",
        BackwashTime: "confirmed: bytes 69-70 = 21:00 vs Aseko Live, serial 110128063",
        ClFree: "confirmed: bytes 16-17 = 0.00 mg/l vs Aseko Live, serial 110128063 (2026-04-28)",
        ClFreeMv: "confirmed: bytes 20-21 = 2 mV, serial 110128063 (2026-04-28)",
        ClPumpRunning: "uncertain: byte[29] 0x40, port may be chlorine or OXY Pure",
        Configuration: "confirmed: byte[4] exact sub-type, 0x02 CLF / 0x03 REDOX (Issue #110)",
        DelayAfterDose: "confirmed: bytes 106-107 = 240 s vs '4 min' in Aseko Live, serial 110128063",
        DelayAfterStartup: "confirmed: bytes 74-75 = 480 s vs '8 min' in Aseko Live, serial 110128063",
        FiltrationPumpRunning: "observed: byte[29] 0x08 clear while Aseko Live showed STOP, serial 110128063; the set state was not captured on firmware A",
        FiltrationSchedule: "n/a: byte[37] is unset on every frame decoded with this profile",
        FlocPumpRunning: "uncertain: byte[29] 0x20 assumed",
        FlowrateAlgicide: "confirmed: byte[103], Issues #110, #115 -- but the same byte is also read as water_level_filling_on, and one of the two must be wrong",
        FlowrateChlor: "confirmed: byte[99], serials 110071590 / 110128063 (Issues #110, #115)",
        FlowrateFloc: "confirmed: byte[101], Issues #110, #115",
        FlowratePhMinus: "confirmed: byte[95] = 60, Aseko Live lists the pH- pump, serial 110128063",
        HeatingActive: "assumed: byte[29] 0x04 per JS-DE-Tech relay_byte bit 2; no HOME frame with the heater running (open item 9)",
        HeatingControlEnabled: "n/a: byte[37] is unset on every frame decoded with this profile",
        MaxFillingTime: "assumed: bytes 76-77 = 10800 s on serial 110128063, plausible (180 min); verified on SALT only",
        Ph: "confirmed: bytes 14-15 = 6.29 vs 6.56 in Aseko Live (later reading), serial 110128063",
        PhMinusConcentration: "confirmed: byte[112], serial 110175608 (Issue #139)",
        PhMinusPumpRunning: "uncertain: byte[29] 0x80 assumed",
        PoolVolume: "confirmed: bytes 92-93 = 60 m3 vs Aseko Live, serial 110128063",
        RequiredAlgicide: "confirmed: byte[72], serial 110128063 (2026-04-28)",
        RequiredClFree: "confirmed: byte[53] / 10 = 0.3 mg/l vs Aseko Live, serial 110128063",
        RequiredFloc: "confirmed: byte[54], serial 110128063 (2026-04-28)",
        RequiredPh: "confirmed: byte[52] / 10 = 7.0 vs Aseko Live, serial 110128063",
        RequiredWaterTemperature: "confirmed: byte[55] is the heating setpoint on serial 110175608 (Issue #135); 25 C with heating disabled on 110128063",
        SerialNumber: "confirmed: bytes 0-3, repeated in every segment header",
        FiltrationStart1: "confirmed: bytes 56-57 = 08:00 last-configured, serial 110128063 (Issues #110, #133)",
        FiltrationStart2: "confirmed: bytes 60-61 = 18:00 last-configured, serial 110128063 (Issues #110, #133)",
        FiltrationStop1: "confirmed: bytes 58-59 = 16:00 last-configured, serial 110128063 (Issues #110, #133)",
        FiltrationStop2: "confirmed: bytes 62-63 = 22:00 last-configured, serial 110128063 (Issues #110, #133)",
        Timestamp: "confirmed: bytes 6-11",
        VspPumpRunning: "confirmed: byte[22] 0x08, serial 110175608",
        WaterFillingActive: "confirmed: byte[29] 0x02 (DomSchCoding #100)",
        WaterFlowToProbes: "confirmed: byte[28] != 0xAA while Aseko Live showed 'NO', serial 110128063",
        WaterLevel: "confirmed: byte[27] (domin211, Issue #110)",
        WaterLevelFillingOff: "confirmed: byte[104] (domin211, DomSchCoding, Issue #110)",
        WaterLevelFillingOn: "unconfirmed: byte[103] = 33 on serial 110128063 is read both as this threshold (cm) and as flowrate_algicide (ml/min); the two mappings cannot both be right",
        WaterLevelHighAlarm: "confirmed: byte[105] (domin211, Issue #110)",
        WaterLevelLowAlarm: "confirmed: byte[102] (domin211, Issue #110)",
        WaterTemperature: "confirmed: bytes 25-26 = 37.9 C vs 38.2 C in Aseko Live (later reading), serial 110128063",
    },
)

# ---------------------------------------------------------------------------
# OXY (ASIN AQUA Oxygen)
# ---------------------------------------------------------------------------

OXY = Profile(
    name="v7 OXY",
    protocol=Protocol.V7,
    model=AsekoDeviceType.OXY,
    features=(
        *_IDENTITY,
        *_MEASUREMENTS,
        Ph,
        *_SETTINGS,
        RequiredOxyDose,
        RequiredFloc,
        RequiredAlgicide,
        FlowrateOxy,
        FlowrateFloc,
        FlowrateAlgicide,
        *_FILTRATION,
        ServiceMenuOpen,
        PhMinusPumpRunning,
        AlgicidePumpRunning,
        FlocPumpRunning,
        OxyPumpRunning,
        *_WATER_LEVEL,
        MaxFillingTime,
        *_UNIT_STATE,
        *_BACKWASH,
        *_ALARMS,
    ),
    overrides={
        Configuration: "decode_v7_ph_and_oxy",
        AlgicidePumpRunning: "decode_v7_oxy",
    },
    evidence={
        AlarmNoFlowToProbes: "unconfirmed: byte[13] was 0x00 in every OXY frame; confirmed on NET and HOME only",
        AlarmOrpTooManyDoses: "unconfirmed: bytes 12-13 were 0x00 in every OXY frame; HOME encoding assumed",
        AlarmPhTooManyDoses: "unconfirmed: bytes 12-13 were 0x00 in every OXY frame; HOME encoding assumed",
        AlarmRapidPhChange: "unconfirmed: byte[13] 0x08 from error_codes.md; never set in the OXY frames",
        AlgicidePumpRunning: "confirmed: byte[29] 0x10, 2026-04-11 Winnetoux log",
        BackwashActive: "assumed: byte[29] 0x01, confirmed on SALT",
        BackwashDuration: "observed: byte[71] * 10 = 100 s on the Winnetoux OXY (serial 110157165); not compared with the app",
        BackwashEveryNDays: "observed: byte[68] = 0 (disabled) on the Winnetoux OXY (serial 110157165); not compared with the app",
        BackwashTime: "observed: bytes 69-70 = 12:30 on the Winnetoux OXY (serial 110157165); not compared with the app",
        Configuration: "confirmed: fixed pH + OXY Pure, the SANOSIL probe sits in the CLF slot",
        DelayAfterDose: "observed: bytes 106-107 = 120 s on the Winnetoux OXY (serial 110157165); not compared with the app",
        DelayAfterStartup: "observed: bytes 74-75 = 240 s on the Winnetoux OXY; the analysis document mislabels byte[73]",
        FiltrationPumpRunning: "confirmed: byte[29] 0x08 in every captured frame",
        FiltrationSchedule: "observed: byte[37] = 0x03 reads nonstop while the Winnetoux OXY ran filtration 24 h; no schedule transition captured",
        FlocPumpRunning: "confirmed: byte[29] 0x20 toggles at the 19:33:52 floc event",
        FlowrateAlgicide: "confirmed: byte[103] = 60 ml/min (2026-04-11)",
        FlowrateFloc: "confirmed: byte[101]",
        FlowrateOxy: "confirmed: byte[99]",
        FlowratePhMinus: "confirmed: byte[95] = 60 ml/min (Winnetoux, oxy_device_analysis.md)",
        HeatingActive: "assumed: byte[29] 0x04 per JS-DE-Tech relay_byte bit 2",
        MaxFillingTime: "assumed: bytes 76-77 = 3600 s on the Winnetoux OXY, plausible (60 min); verified on SALT only",
        OxyPumpRunning: "confirmed: byte[29] 0x40, 2026-04-11 Winnetoux log",
        Ph: "observed: bytes 14-15 = 7.17 on the Winnetoux OXY (serial 110157165); not compared with the app",
        PhMinusConcentration: "assumed: byte[112], confirmed on HOME",
        PhMinusPumpRunning: "confirmed: byte[29] 0x80, 2026-04-12 Winnetoux log",
        PoolVolume: "observed: bytes 92-93 = 41 m3 on the Winnetoux OXY (serial 110157165); not compared with the app",
        RequiredAlgicide: "confirmed: byte[72] = 15 (2026-04-11)",
        RequiredFloc: "confirmed: byte[54] = 10 (2026-04-11)",
        RequiredOxyDose: "confirmed: byte[53] (Winnetoux, 2026-04-11)",
        RequiredPh: "observed: byte[52] / 10 = 7.2 on the Winnetoux OXY (serial 110157165); not compared with the app",
        RequiredWaterTemperature: "observed: byte[55] = 25 C on the Winnetoux OXY (serial 110157165); not compared with the app",
        SerialNumber: "confirmed: bytes 0-3, repeated in every segment header",
        ServiceMenuOpen: "observed: byte[37] bit 0x04 clear in every OXY frame; the menu never captured open",
        FiltrationStart1: "observed: bytes 56-57 = 08:00 in every frame on the Winnetoux OXY (serial 110157165); not compared with the app",
        FiltrationStart2: "observed: bytes 60-61 = 18:00 in every frame on the Winnetoux OXY (serial 110157165); not compared with the app",
        FiltrationStop1: "observed: bytes 58-59 = 16:00 in every frame on the Winnetoux OXY (serial 110157165); not compared with the app",
        FiltrationStop2: "observed: bytes 62-63 = 22:00 in every frame on the Winnetoux OXY (serial 110157165); not compared with the app",
        Timestamp: "confirmed: bytes 6-11",
        VspPumpRunning: "assumed: byte[22] 0x08, confirmed on HOME",
        WaterFillingActive: "assumed: byte[29] 0x02, confirmed on HOME",
        WaterFlowToProbes: "observed: byte[28] = 0xAA on the Winnetoux OXY (serial 110157165); not compared with the app",
        WaterLevel: "assumed: byte[27], confirmed on HOME",
        WaterLevelFillingOn: "unconfirmed: byte[103] is flowrate_algicide on OXY (confirmed, 60 ml/min); reading it as a level threshold too cannot be right",
        WaterTemperature: "observed: bytes 25-26 = 9.5 C on the Winnetoux OXY (serial 110157165); not compared with the app",
    },
)

# ---------------------------------------------------------------------------
# NET (Aqua NET): measurement and dosing only, no filter, no valve
# ---------------------------------------------------------------------------

NET = Profile(
    name="v7 NET",
    protocol=Protocol.V7,
    model=AsekoDeviceType.NET,
    features=(
        *_IDENTITY,
        *_MEASUREMENTS,
        *_CHLORINE_PROBES,
        *_SETTINGS,
        *_DISINFECTION_SETPOINTS,
        RequiredAlgicide,
        RequiredFloc,
        FlowrateChlor,
        FlowrateAlgicide,
        FlowrateFloc,
        ClPumpRunning,
        PhMinusPumpRunning,
        *_ALARMS,
    ),
    overrides={
        **_SHARED_THIRD_PUMP,
        ClPumpRunning: "decode_v7_net",
        PhMinusPumpRunning: "decode_v7_net",
    },
    evidence={
        AlarmNoFlowToProbes: "confirmed: byte[13] 0x04 (DomSchCoding, NET frame)",
        AlarmOrpTooManyDoses: "unconfirmed: byte[12] is 0x00 on NET; HOME encodings assumed",
        AlarmPhTooManyDoses: "unconfirmed: byte[12] is 0x00 on NET; HOME encodings assumed",
        AlarmRapidPhChange: "unconfirmed: byte[13] 0x08 from error_codes.md; never set on NET",
        ClFree: "confirmed: bytes 16-17 / 100",
        ClFreeMv: "confirmed: bytes 20-21",
        ClPumpRunning: "confirmed: byte[29] 0x02 (Issue #66)",
        Configuration: "confirmed: byte[4] missing-probe bits (0x09 CLF, 0x0A REDOX, 0x0B DOSE)",
        DelayAfterDose: "observed: bytes 106-107 on the Issue #66 NET; not compared with the app",
        DelayAfterStartup: "observed: bytes 74-75 on the Issue #66 NET; not compared with the app",
        FlowrateAlgicide: "unverified: byte[37] and byte[101] are 0xFF on every NET frame; no third pump",
        FlowrateChlor: "confirmed: byte[99] (net_device_analysis.md)",
        FlowrateFloc: "unverified: byte[37] and byte[101] are 0xFF on every NET frame; no third pump",
        FlowratePhMinus: "confirmed: byte[95] (Issue #110, #115)",
        Ph: "confirmed: bytes 14-15 / 100 (Issue #66 frames)",
        PhMinusPumpRunning: "confirmed: byte[29] 0x01 (Issue #66)",
        PoolVolume: "observed: bytes 92-93 on the Issue #66 NET; not compared with the app",
        RequiredAlgicide: "unverified: byte[37] is 0xFF on every NET frame, so the shared-port reading never applies",
        RequiredClDose: "observed: byte[53] = 5 ml/m3/h in DOSE mode (2026-04-07 capture); not compared with the app",
        RequiredClFree: "observed: byte[53] / 10 on the Issue #66 NET; not compared with the app",
        RequiredFloc: "unverified: byte[37] is 0xFF on every NET frame, so the shared-port reading never applies",
        RequiredPh: "confirmed: byte[52] / 10 (Issue #66 frames)",
        RequiredRedox: "unverified: byte[53] * 10 on a REDOX NET; no such frame captured",
        RequiredWaterTemperature: "n/a: byte[55] is 0xFF on NET, which has no water temperature setpoint",
        SerialNumber: "confirmed: bytes 0-3, repeated in every segment header",
        Timestamp: "n/a: bytes 6-11 are 0xFF on every NET frame, Home Assistant's clock is used instead",
        WaterFlowToProbes: "confirmed: byte[28] == 0xAA (Issue #66 frames)",
        WaterTemperature: "confirmed: bytes 25-26 / 10 (Issue #66 frames)",
    },
)

# ---------------------------------------------------------------------------
# PROFI: unit type 0x10, unconfirmed
# ---------------------------------------------------------------------------

PROFI = Profile(
    name="v7 PROFI",
    protocol=Protocol.V7,
    model=AsekoDeviceType.PROFI,
    features=(
        *_IDENTITY,
        *_MEASUREMENTS,
        *_CHLORINE_PROBES,
        *_SETTINGS,
        RequiredClFree,
        RequiredClDose,
        FlowrateChlor,
        FlowrateAlgicide,
        FlowrateFloc,
        *_FILTRATION,
        ServiceMenuOpen,
        ClPumpRunning,
        PhMinusPumpRunning,
        FlocPumpRunning,
        *_WATER_LEVEL,
        *_UNIT_STATE,
        *_BACKWASH,
        *_ALARMS,
    ),
    overrides={
        Configuration: "decode_v7_without_dose",
        FlowrateAlgicide: "decode_v7_routed_by_byte37",
        FlowrateFloc: "decode_v7_routed_by_byte37",
    },
    evidence={
        AlarmNoFlowToProbes: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        AlarmOrpTooManyDoses: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        AlarmPhTooManyDoses: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        AlarmRapidPhChange: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        BackwashActive: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        BackwashDuration: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        BackwashEveryNDays: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        BackwashTime: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        ClFree: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        ClFreeMv: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        ClPumpRunning: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        Configuration: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        DelayAfterDose: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        DelayAfterStartup: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FiltrationPumpRunning: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FiltrationSchedule: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FlocPumpRunning: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FlowrateAlgicide: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FlowrateChlor: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FlowrateFloc: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FlowratePhMinus: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        HeatingActive: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        Ph: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        PhMinusConcentration: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        PhMinusPumpRunning: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        PoolVolume: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        Redox: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        RequiredClDose: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        RequiredClFree: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        RequiredPh: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        RequiredWaterTemperature: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        SerialNumber: "confirmed: bytes 0-3, repeated in every segment header",
        ServiceMenuOpen: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FiltrationStart1: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FiltrationStart2: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FiltrationStop1: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FiltrationStop2: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        Timestamp: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        VspPumpRunning: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        WaterFillingActive: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        WaterFlowToProbes: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        WaterLevel: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        WaterLevelFillingOff: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        WaterLevelFillingOn: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        WaterLevelHighAlarm: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        WaterLevelLowAlarm: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        WaterTemperature: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
    },
)

# ---------------------------------------------------------------------------
# A unit type nobody has mapped.  Read everything that has a generic v7
# reading -- every probe, the shared-port layout most models use, the
# default actuator bits -- so that the diagnostics of such a unit show as
# much as the frame can be made to say.  Nothing here is verified for the
# unit at hand: the coordinator keeps it out of the entity platforms and
# reports it separately in diagnostics as unrecognised.
#
# Left out are readings whose bytes mean something else on other models and
# so cannot be called generic: SALT's electrolyser and salinity (bytes 20-21
# are cl_free_mv elsewhere), the OXY dose and pump (byte[53] and bit 0x40
# are chlorine elsewhere), HOME's heating / antifreeze enables (byte[37] 0x80
# is the algicide routing elsewhere) and the air temperature, verified on
# SALT only.
# ---------------------------------------------------------------------------

_UNKNOWN_FEATURES = (
    *_IDENTITY,
    *_MEASUREMENTS,
    *_CHLORINE_PROBES,
    *_SETTINGS,
    *_DISINFECTION_SETPOINTS,
    RequiredAlgicide,
    RequiredFloc,
    FlowrateChlor,
    FlowrateAlgicide,
    FlowrateFloc,
    *_FILTRATION,
    ServiceMenuOpen,
    ClPumpRunning,
    PhMinusPumpRunning,
    AlgicidePumpRunning,
    FlocPumpRunning,
    *_WATER_LEVEL,
    MaxFillingTime,
    *_UNIT_STATE,
    *_BACKWASH,
    *_ALARMS,
)

UNKNOWN = Profile(
    name="v7 unknown unit type",
    protocol=Protocol.V7,
    model=None,
    features=_UNKNOWN_FEATURES,
    overrides={
        Configuration: "decode_v7_all_probes",
        **_SHARED_THIRD_PUMP,
    },
    evidence={
        AlarmNoFlowToProbes: "unverified: unmapped unit type, read with the generic v7 reading",
        AlarmOrpTooManyDoses: "unverified: unmapped unit type, read with the generic v7 reading",
        AlarmPhTooManyDoses: "unverified: unmapped unit type, read with the generic v7 reading",
        AlarmRapidPhChange: "unverified: unmapped unit type, read with the generic v7 reading",
        AlgicidePumpRunning: "unverified: unmapped unit type, read with the generic v7 reading",
        BackwashActive: "unverified: unmapped unit type, read with the generic v7 reading",
        BackwashDuration: "unverified: unmapped unit type, read with the generic v7 reading",
        BackwashEveryNDays: "unverified: unmapped unit type, read with the generic v7 reading",
        BackwashTime: "unverified: unmapped unit type, read with the generic v7 reading",
        ClFree: "unverified: unmapped unit type, read with the generic v7 reading",
        ClFreeMv: "unverified: unmapped unit type, read with the generic v7 reading",
        ClPumpRunning: "unverified: unmapped unit type, read with the generic v7 reading",
        Configuration: "unverified: unmapped unit type, read with the generic v7 reading",
        DelayAfterDose: "unverified: unmapped unit type, read with the generic v7 reading",
        DelayAfterStartup: "unverified: unmapped unit type, read with the generic v7 reading",
        FiltrationPumpRunning: "unverified: unmapped unit type, read with the generic v7 reading",
        FiltrationSchedule: "unverified: unmapped unit type, read with the generic v7 reading",
        FlocPumpRunning: "unverified: unmapped unit type, read with the generic v7 reading",
        FlowrateAlgicide: "unverified: unmapped unit type, read with the generic v7 reading",
        FlowrateChlor: "unverified: unmapped unit type, read with the generic v7 reading",
        FlowrateFloc: "unverified: unmapped unit type, read with the generic v7 reading",
        FlowratePhMinus: "unverified: unmapped unit type, read with the generic v7 reading",
        HeatingActive: "unverified: unmapped unit type, read with the generic v7 reading",
        MaxFillingTime: "unverified: unmapped unit type, read with the generic v7 reading",
        Ph: "unverified: unmapped unit type, read with the generic v7 reading",
        PhMinusConcentration: "unverified: unmapped unit type, read with the generic v7 reading",
        PhMinusPumpRunning: "unverified: unmapped unit type, read with the generic v7 reading",
        PoolVolume: "unverified: unmapped unit type, read with the generic v7 reading",
        Redox: "unverified: unmapped unit type, read with the generic v7 reading",
        RequiredAlgicide: "unverified: unmapped unit type, read with the generic v7 reading",
        RequiredClDose: "unverified: unmapped unit type, read with the generic v7 reading",
        RequiredClFree: "unverified: unmapped unit type, read with the generic v7 reading",
        RequiredFloc: "unverified: unmapped unit type, read with the generic v7 reading",
        RequiredPh: "unverified: unmapped unit type, read with the generic v7 reading",
        RequiredRedox: "unverified: unmapped unit type, read with the generic v7 reading",
        RequiredWaterTemperature: "unverified: unmapped unit type, read with the generic v7 reading",
        SerialNumber: "unverified: unmapped unit type, read with the generic v7 reading",
        ServiceMenuOpen: "unverified: unmapped unit type, read with the generic v7 reading",
        FiltrationStart1: "unverified: unmapped unit type, read with the generic v7 reading",
        FiltrationStart2: "unverified: unmapped unit type, read with the generic v7 reading",
        FiltrationStop1: "unverified: unmapped unit type, read with the generic v7 reading",
        FiltrationStop2: "unverified: unmapped unit type, read with the generic v7 reading",
        Timestamp: "unverified: unmapped unit type, read with the generic v7 reading",
        VspPumpRunning: "unverified: unmapped unit type, read with the generic v7 reading",
        WaterFillingActive: "unverified: unmapped unit type, read with the generic v7 reading",
        WaterFlowToProbes: "unverified: unmapped unit type, read with the generic v7 reading",
        WaterLevel: "unverified: unmapped unit type, read with the generic v7 reading",
        WaterLevelFillingOff: "unverified: unmapped unit type, read with the generic v7 reading",
        WaterLevelFillingOn: "unverified: unmapped unit type, read with the generic v7 reading",
        WaterLevelHighAlarm: "unverified: unmapped unit type, read with the generic v7 reading",
        WaterLevelLowAlarm: "unverified: unmapped unit type, read with the generic v7 reading",
        WaterTemperature: "unverified: unmapped unit type, read with the generic v7 reading",
    },
)

BY_MODEL: dict[AsekoDeviceType | None, Profile] = {
    AsekoDeviceType.SALT: SALT,
    AsekoDeviceType.OXY: OXY,
    AsekoDeviceType.NET: NET,
    AsekoDeviceType.PROFI: PROFI,
    None: UNKNOWN,
}
