#!/usr/bin/env python3
"""Look at a firmware v7 (binary, 120 bytes) Aseko frame byte by byte.

Usage:
    python scripts/hex_tools.py HEX --table
    python scripts/hex_tools.py HEX --tablewrite hex_table.md
    python scripts/hex_tools.py HEX --byteinfo 14
    python scripts/hex_tools.py HEX --generate-test

HEX is the frame as hex, spaces allowed (e.g. ``raw_frame_v7.hex_dump`` from a
diagnostics download).  What a byte means is the profile's business (see
docs/support_matrix.md and docs/decoding-by-device-profile.md); this tool only
shows the bytes, so it never repeats an outdated byte map.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

FRAME_SIZE = 120


def parse_hex(text: str) -> bytes:
    """The frame bytes from a hex string; spaces and a ``0x`` prefix allowed."""
    cleaned = text.replace(" ", "").replace("\n", "").removeprefix("0x")
    try:
        return bytes.fromhex(cleaned)
    except ValueError as exc:
        raise SystemExit(f"not a hex string: {exc}") from exc


def table_rows(data: bytes) -> list[tuple[int, int, int | None]]:
    """(index, byte, big-endian word of this and the next byte or None)."""
    return [
        (i, b, int.from_bytes(data[i : i + 2], "big") if i + 1 < len(data) else None)
        for i, b in enumerate(data)
    ]


def print_hex_table(data: bytes) -> None:
    """Print every byte: index, hex, decimal and the word starting there."""
    print("Byte | HEX | Dec | Word (BE)")
    print("-----|-----|-----|----------")
    for i, b, word in table_rows(data):
        print(f"{i:03d}  | {b:02x}  | {b:3d} | {'N/A' if word is None else word}")


def write_hex_table_md(data: bytes, path: Path) -> None:
    """Write the same table as Markdown."""
    lines = ["| Byte | HEX | Dec | Word (BE) |", "|---|---|---|---|"]
    lines += [
        f"| {i:03d} | {b:02x} | {b} | {'N/A' if word is None else word} |"
        for i, b, word in table_rows(data)
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def byte_info(data: bytes, index: int) -> str:
    """One byte in hex and decimal, and the big-endian word starting at it."""
    if not 0 <= index < len(data):
        raise SystemExit(f"byte index {index} is outside the frame (0-{len(data) - 1})")
    b = data[index]
    text = f"byte[{index}] = 0x{b:02x} = {b} = 0b{b:08b}"
    if index + 1 < len(data):
        word = int.from_bytes(data[index : index + 2], "big")
        text += f" / word[{index}-{index + 1}] = 0x{word:04x} = {word}"
    return text


def generate_test(data: bytes) -> str:
    """A pytest skeleton for this frame.

    The expected values are left as TODOs on purpose: they must come from
    what the unit showed when the frame was sent, not from the decoder under
    test.
    """
    hex_lines = [data[i : i + 20].hex(" ") for i in range(0, len(data), 20)]
    out = [
        "# --- generated by scripts/hex_tools.py --generate-test ---",
        "# Fill in the expected values from the unit's display or the Aseko app",
        "# at the moment the frame was sent.",
        "",
        "from custom_components.aseko_local.decoding import decode",
        "",
        "FRAME = bytes.fromhex(",
        *(f'    "{line} "' for line in hex_lines),
        ")",
        "",
        "",
        "def test_decoded_frame():",
        "    device = decode(FRAME)",
        "",
        f"    assert device.serial_number == {int.from_bytes(data[0:4], 'big')}",
        "    # TODO: assert the values the unit showed, e.g.",
        "    # assert device.ph == pytest.approx(7.2)",
    ]
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("hex", help="the frame as hex (spaces allowed)")
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--table", action="store_true", help="print every byte")
    action.add_argument(
        "--tablewrite", type=Path, metavar="FILE", help="write the table as Markdown"
    )
    action.add_argument(
        "--byteinfo", type=int, metavar="N", help="one byte and the word starting at it"
    )
    action.add_argument(
        "--generate-test", action="store_true", help="print a pytest skeleton"
    )
    args = parser.parse_args(argv)

    data = parse_hex(args.hex)
    if len(data) != FRAME_SIZE:
        print(
            f"warning: {len(data)} bytes, a v7 frame has {FRAME_SIZE}", file=sys.stderr
        )

    if args.table:
        print_hex_table(data)
    elif args.tablewrite is not None:
        write_hex_table_md(data, args.tablewrite)
        print(f"wrote {args.tablewrite}")
    elif args.byteinfo is not None:
        print(byte_info(data, args.byteinfo))
    else:
        print(generate_test(data), end="")


if __name__ == "__main__":
    main()
