#!/usr/bin/env python3
"""Look at a firmware v8 (text) Aseko frame section by section.

Usage:
    python scripts/v8_tools.py '{v1 110203680 ...}' --annotate
    python scripts/v8_tools.py '{v1 110203680 ...}' --generate-test

The frame is the whole text including the braces.  Standalone: it does not
import Home Assistant or the integration.  Its section parser follows the
integration's (``decoding/frames/v8.py``): ``crc16`` is hexadecimal, every
other section decimal, and a token that is not a number reads None without
losing the rest of its section; ``tests/test_scripts.py`` keeps the two alike.
"""

from __future__ import annotations

import argparse
import re

SENTINEL = -500  # the v8 "not fitted / not measured" marker

# What the integration reads where (decoding/features, v8 readings).  Only a
# guide for reading a frame; the profiles and docs/support_matrix.md decide.
FIELD_MAP: dict[str, dict[int, tuple[str, str]]] = {
    "ins": {
        0: ("water_temperature", "/ 10 -> degC"),
        8: ("water_flow_to_probes", "1 = water flows"),
        16: ("unit_clock hour", "the unit's clock"),
        17: ("unit_clock minute", "the unit's clock"),
    },
    "ains": {
        0: ("ph", "/ 100"),
        6: ("redox", "mV"),
    },
    "outs": {
        2: ("filtration_running", "1 = on"),
        8: ("ph_minus_pump_running", "unconfirmed"),
        9: ("chlorine_pump_running", "unconfirmed (NET)"),
    },
    "areqs": {
        0: ("ph_target", "/ 10"),
        1: ("redox_target", "* 10 -> mV"),
        14: ("pool_volume", "m3"),
        17: ("startup_delay", "minutes"),
        18: ("dosing_delay", "minutes"),
    },
}

_SECTION_RE = re.compile(r"(\w+):\s*(.*?)(?=\s+\w+:|$)", re.DOTALL)
_HEADER_RE = re.compile(r"v1\s+(\d+)\s+(\d+)\s+(\S+)\s+(\S+)")


def model_from_header_type(header_type: int) -> str | None:
    """The model the header type names (as the integration's v8 profiles do)."""
    if 800 <= header_type <= 899:
        return "NET"
    if 100 <= header_type <= 199:
        return "SALT"
    return None


def parse_v8_frame(
    text: str,
) -> tuple[dict[str, str | int], dict[str, list[int | None]]]:
    """(header, sections) of a v8 frame; raises ValueError when it is not one."""
    text = text.strip()
    if not text.startswith("{") or not text.endswith("}"):
        raise ValueError("a v8 frame starts with '{' and ends with '}'")
    body = text[1:-1].strip()
    match = _HEADER_RE.match(body)
    if not match:
        raise ValueError(f"header not recognised: {body[:60]!r}")
    header: dict[str, str | int] = {
        "serial": int(match.group(1)),
        "type": int(match.group(2)),
        "f3": match.group(3),
        "f4": match.group(4),
    }
    sections: dict[str, list[int | None]] = {}
    for section in _SECTION_RE.finditer(body):
        name = section.group(1)
        if name == "v1":
            continue
        base = 16 if name == "crc16" else 10
        values: list[int | None] = []
        for token in section.group(2).split():
            try:
                values.append(int(token, base))
            except ValueError:
                values.append(None)
        sections[name] = values
    return header, sections


def annotate(text: str) -> str:
    """Every section, value by value, with what the integration reads there."""
    header, sections = parse_v8_frame(text)
    model = model_from_header_type(int(header["type"]))
    out = [
        f"serial = {header['serial']}",
        f"type   = {header['type']} ({model or 'unknown model'})",
        f"f3     = {header['f3']}  f4 = {header['f4']}  (unknown)",
        "",
    ]
    for name, values in sections.items():
        known = FIELD_MAP.get(name, {})
        out.append(f"[{name}]")
        for i, value in enumerate(values):
            field, note = known.get(i, ("", ""))
            if value is None:
                shown, mark = "?", "  <- not a number"
            elif name == "crc16":
                shown, mark = f"0x{value:04x}", ""
            else:
                shown, mark = (
                    str(value),
                    "  <- absent (-500)" if value == SENTINEL else "",
                )
            out.append(f"  [{i:>2}] {shown:>7}  {field:<24} {note}{mark}".rstrip())
        out.append("")
    return "\n".join(out)


def generate_test(text: str) -> str:
    """A pytest skeleton; expected values are TODOs to fill in from the unit."""
    header, _ = parse_v8_frame(text)
    model = model_from_header_type(int(header["type"]))
    frame = text.strip()
    chunks = [frame[i : i + 70] for i in range(0, len(frame), 70)]
    out = [
        "# --- generated by scripts/v8_tools.py --generate-test ---",
        "# Fill in the expected values from the unit's display or the Aseko app",
        "# at the moment the frame was sent.",
        "",
        "from custom_components.aseko_local.decoding import decode",
        "from custom_components.aseko_local.models import AsekoDeviceType",
        "",
        "FRAME = (",
        *(f'    b"{chunk}"' for chunk in chunks),
        '    b"\\n"',
        ")",
        "",
        "",
        "def test_decoded_frame():",
        "    device = decode(FRAME)",
        "",
        f"    assert device.serial_number == {header['serial']}",
    ]
    if model is not None:
        out.append(f"    assert device.device_type == AsekoDeviceType.{model}")
    else:
        out.append(
            f"    # header type {header['type']} names no known model: "
            "the unknown profile reads it"
        )
    out += [
        "    # TODO: assert the values the unit showed, e.g.",
        "    # assert device.ph == pytest.approx(7.2)",
    ]
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("frame", help="the whole v8 frame text, braces included")
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--annotate", action="store_true", help="annotate every value")
    action.add_argument(
        "--generate-test", action="store_true", help="print a pytest skeleton"
    )
    args = parser.parse_args(argv)
    try:
        print(annotate(args.frame) if args.annotate else generate_test(args.frame))
    except ValueError as exc:
        parser.error(str(exc))


if __name__ == "__main__":
    main()
