"""v7 profile: ASIN AQUA Profi: unit type 0x10, unconfirmed."""

from __future__ import annotations

from ....models import AsekoDeviceType
from ...features import (
    AlarmMaxDisinfectionDose,
    AlarmNoFlowToProbes,
    AlarmPhDosingIneffective,
    AlarmRapidPhChange,
    BackwashDuration,
    BackwashInterval,
    BackwashRunning,
    BackwashStartTime,
    ChlorineDoseTarget,
    ChlorineFlowRate,
    ChlorinePumpRunning,
    Configuration,
    DosingDelay,
    FiltrationPeriod1End,
    FiltrationPeriod1Start,
    FiltrationPeriod2End,
    FiltrationPeriod2Start,
    FiltrationRunning,
    FiltrationSchedule,
    FlocculantDoseTarget,
    FlocculantFlowRate,
    FlocculantPumpRunning,
    FreeChlorine,
    FreeChlorineMv,
    FreeChlorineTarget,
    HeatingRunning,
    MaxPhDoses,
    MaxRefillTime,
    Ph,
    PhMinusConcentration,
    PhMinusFlowRate,
    PhMinusPumpRunning,
    PhTarget,
    PoolVolume,
    Redox,
    Refilling,
    SerialNumber,
    ServiceMenuOpen,
    StartupDelay,
    Timestamp,
    WaterFlowToProbes,
    WaterLevel,
    WaterLevelHighAlarm,
    WaterLevelLowAlarm,
    WaterLevelRefillStart,
    WaterLevelRefillStop,
    WaterTemperature,
    WaterTemperatureTarget,
)
from ...frames import Protocol
from ...profile import Profile
from .common import (
    ALARMS,
    BACKWASH,
    CHLORINE_PROBES,
    FILTRATION,
    IDENTITY,
    MEASUREMENTS,
    SETTINGS,
    WATER_LEVEL,
)

PROFI = Profile(
    name="v7 PROFI",
    protocol=Protocol.V7,
    model=AsekoDeviceType.PROFI,
    features=(
        *IDENTITY,
        *MEASUREMENTS,
        *CHLORINE_PROBES,
        *SETTINGS,
        FreeChlorineTarget,
        ChlorineDoseTarget,
        FlocculantDoseTarget,
        ChlorineFlowRate,
        FlocculantFlowRate,
        *FILTRATION,
        ServiceMenuOpen,
        ChlorinePumpRunning,
        PhMinusPumpRunning,
        FlocculantPumpRunning,
        *WATER_LEVEL,
        MaxRefillTime,
        HeatingRunning,
        PhMinusConcentration,
        MaxPhDoses,
        *BACKWASH,
        *ALARMS,
    ),
    overrides={
        Configuration: "decode_v7_without_dose",
        FlocculantDoseTarget: "decode_v7_routed_by_byte37",
        FlocculantFlowRate: "decode_v7_routed_by_byte37",
    },
    evidence={
        AlarmNoFlowToProbes: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        AlarmMaxDisinfectionDose: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        AlarmPhDosingIneffective: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        AlarmRapidPhChange: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        BackwashRunning: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        BackwashDuration: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        BackwashInterval: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        BackwashStartTime: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FreeChlorine: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FreeChlorineMv: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        ChlorinePumpRunning: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        Configuration: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        DosingDelay: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        StartupDelay: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FiltrationRunning: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FiltrationSchedule: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FlocculantPumpRunning: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        ChlorineFlowRate: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FlocculantFlowRate: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        PhMinusFlowRate: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        HeatingRunning: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        Ph: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        MaxRefillTime: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md); the 2021 PROFI manual lists a max. filling time",
        MaxPhDoses: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        PhMinusConcentration: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        PhMinusPumpRunning: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        PoolVolume: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        Redox: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        ChlorineDoseTarget: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FlocculantDoseTarget: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md); the PROFI setpoints screen has a flocculant dose (ml/24 h m3) on its shared flocculant / algicide output",
        FreeChlorineTarget: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        PhTarget: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        WaterTemperatureTarget: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        SerialNumber: "derived: bytes 0-3, repeated in every segment header -- the v7 frame layout every unit shares; no PROFI frame has been captured",
        ServiceMenuOpen: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FiltrationPeriod1Start: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FiltrationPeriod2Start: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FiltrationPeriod1End: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        FiltrationPeriod2End: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        Timestamp: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        Refilling: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        WaterFlowToProbes: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        WaterLevel: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        WaterLevelRefillStop: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        WaterLevelRefillStart: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        WaterLevelHighAlarm: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        WaterLevelLowAlarm: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
        WaterTemperature: "assumed: no real PROFI frame has been captured; layout inferred from the manual and the other models (profi_device_analysis.md)",
    },
)
