"""v7 profile for a unit type nobody has mapped.

Read everything that has a generic v7
reading -- every probe, the shared-port layout most models use, the
default actuator bits -- so that the diagnostics of such a unit show as
much as the frame can be made to say.  Nothing here is verified for the
unit at hand: the coordinator keeps it out of the entity platforms and
reports it separately in diagnostics as unrecognised.

Left out are readings whose bytes mean something else on other models and
so cannot be called generic: SALT's electrolyser and salinity (bytes 20-21
are free_chlorine_mv elsewhere), the OXY dose and pump (byte[53] and bit 0x40
are chlorine elsewhere) and HOME's heating / antifreeze enables (byte[37]
0x80 is the algicide routing elsewhere).  Air temperature is left out too:
NET carries unrelated data in bytes 23-24.
"""

from __future__ import annotations

from ...decoders import (
    AlarmMaxDisinfectionDose,
    AlarmNoFlowToProbes,
    AlarmPhDosingIneffective,
    AlarmRapidPhChange,
    AlgaecideDoseTarget,
    AlgaecideFlowRate,
    AlgaecidePumpRunning,
    BackwashDuration,
    BackwashInterval,
    BackwashRunning,
    BackwashStartTime,
    ChlorineDoseTarget,
    ChlorineFlowRate,
    ChlorinePumpRunning,
    Configuration,
    DosingDelay,
    FiltrationPeriod1End,
    FiltrationPeriod1Start,
    FiltrationPeriod2End,
    FiltrationPeriod2Start,
    FiltrationRunning,
    FiltrationSchedule,
    FlocculantDoseTarget,
    FlocculantFlowRate,
    FlocculantPumpRunning,
    FreeChlorine,
    FreeChlorineMv,
    FreeChlorineTarget,
    HeatingRunning,
    MaxPhDoses,
    MaxRefillTime,
    Ph,
    PhMinusConcentration,
    PhMinusFlowRate,
    PhMinusPumpRunning,
    PhTarget,
    PoolVolume,
    Redox,
    RedoxTarget,
    Refilling,
    SerialNumber,
    ServiceMenuOpen,
    StartupDelay,
    Timestamp,
    VariableSpeedPumpEnabled,
    WaterFlowToProbes,
    WaterLevel,
    WaterLevelHighAlarm,
    WaterLevelLowAlarm,
    WaterLevelRefillStart,
    WaterLevelRefillStop,
    WaterTemperature,
    WaterTemperatureTarget,
)
from ...frame import Protocol
from ...profile import Profile
from .common import (
    ALARMS,
    BACKWASH,
    CHLORINE_PROBES,
    DISINFECTION_SETPOINTS,
    FILTRATION,
    IDENTITY,
    MEASUREMENTS,
    SETTINGS,
    SHARED_THIRD_PUMP,
    UNIT_STATE,
    WATER_LEVEL,
)

_UNKNOWN_FEATURES = (
    *IDENTITY,
    *MEASUREMENTS,
    *CHLORINE_PROBES,
    *SETTINGS,
    *DISINFECTION_SETPOINTS,
    AlgaecideDoseTarget,
    FlocculantDoseTarget,
    ChlorineFlowRate,
    AlgaecideFlowRate,
    FlocculantFlowRate,
    *FILTRATION,
    ServiceMenuOpen,
    ChlorinePumpRunning,
    PhMinusPumpRunning,
    AlgaecidePumpRunning,
    FlocculantPumpRunning,
    *WATER_LEVEL,
    MaxRefillTime,
    MaxPhDoses,
    *UNIT_STATE,
    *BACKWASH,
    *ALARMS,
)

UNKNOWN = Profile(
    name="v7 unknown unit type",
    protocol=Protocol.V7,
    model=None,
    features=_UNKNOWN_FEATURES,
    overrides={
        Configuration: "decode_v7_all_probes",
        **SHARED_THIRD_PUMP,
    },
    evidence={
        AlarmNoFlowToProbes: "unverified: unmapped unit type, read with the generic v7 reading",
        AlarmMaxDisinfectionDose: "unverified: unmapped unit type, read with the generic v7 reading",
        AlarmPhDosingIneffective: "unverified: unmapped unit type, read with the generic v7 reading",
        AlarmRapidPhChange: "unverified: unmapped unit type, read with the generic v7 reading",
        AlgaecidePumpRunning: "unverified: unmapped unit type, read with the generic v7 reading",
        BackwashRunning: "unverified: unmapped unit type, read with the generic v7 reading",
        BackwashDuration: "unverified: unmapped unit type, read with the generic v7 reading",
        BackwashInterval: "unverified: unmapped unit type, read with the generic v7 reading",
        BackwashStartTime: "unverified: unmapped unit type, read with the generic v7 reading",
        FreeChlorine: "unverified: unmapped unit type, read with the generic v7 reading",
        FreeChlorineMv: "unverified: unmapped unit type, read with the generic v7 reading",
        ChlorinePumpRunning: "unverified: unmapped unit type, read with the generic v7 reading",
        Configuration: "unverified: unmapped unit type, read with the generic v7 reading",
        DosingDelay: "unverified: unmapped unit type, read with the generic v7 reading",
        StartupDelay: "unverified: unmapped unit type, read with the generic v7 reading",
        FiltrationRunning: "unverified: unmapped unit type, read with the generic v7 reading",
        FiltrationSchedule: "unverified: unmapped unit type, read with the generic v7 reading",
        FlocculantPumpRunning: "unverified: unmapped unit type, read with the generic v7 reading",
        AlgaecideFlowRate: "unverified: unmapped unit type, read with the generic v7 reading",
        ChlorineFlowRate: "unverified: unmapped unit type, read with the generic v7 reading",
        FlocculantFlowRate: "unverified: unmapped unit type, read with the generic v7 reading",
        PhMinusFlowRate: "unverified: unmapped unit type, read with the generic v7 reading",
        HeatingRunning: "unverified: unmapped unit type, read with the generic v7 reading",
        MaxRefillTime: "unverified: unmapped unit type, read with the generic v7 reading",
        Ph: "unverified: unmapped unit type, read with the generic v7 reading",
        PhMinusConcentration: "unverified: unmapped unit type, read with the generic v7 reading",
        PhMinusPumpRunning: "unverified: unmapped unit type, read with the generic v7 reading",
        PoolVolume: "unverified: unmapped unit type, read with the generic v7 reading",
        Redox: "unverified: unmapped unit type, read with the generic v7 reading",
        AlgaecideDoseTarget: "unverified: unmapped unit type, read with the generic v7 reading",
        ChlorineDoseTarget: "unverified: unmapped unit type, read with the generic v7 reading",
        FreeChlorineTarget: "unverified: unmapped unit type, read with the generic v7 reading",
        FlocculantDoseTarget: "unverified: unmapped unit type, read with the generic v7 reading",
        PhTarget: "unverified: unmapped unit type, read with the generic v7 reading",
        RedoxTarget: "unverified: unmapped unit type, read with the generic v7 reading",
        WaterTemperatureTarget: "unverified: unmapped unit type, read with the generic v7 reading",
        SerialNumber: "unverified: unmapped unit type, read with the generic v7 reading",
        ServiceMenuOpen: "unverified: unmapped unit type, read with the generic v7 reading",
        FiltrationPeriod1Start: "unverified: unmapped unit type, read with the generic v7 reading",
        FiltrationPeriod2Start: "unverified: unmapped unit type, read with the generic v7 reading",
        FiltrationPeriod1End: "unverified: unmapped unit type, read with the generic v7 reading",
        FiltrationPeriod2End: "unverified: unmapped unit type, read with the generic v7 reading",
        Timestamp: "unverified: unmapped unit type, read with the generic v7 reading",
        VariableSpeedPumpEnabled: "unverified: unmapped unit type, read with the generic v7 reading",
        Refilling: "unverified: unmapped unit type, read with the generic v7 reading",
        WaterFlowToProbes: "unverified: unmapped unit type, read with the generic v7 reading",
        WaterLevel: "unverified: unmapped unit type, read with the generic v7 reading",
        WaterLevelRefillStop: "unverified: unmapped unit type, read with the generic v7 reading",
        WaterLevelRefillStart: "unverified: unmapped unit type, read with the generic v7 reading",
        WaterLevelHighAlarm: "unverified: unmapped unit type, read with the generic v7 reading",
        WaterLevelLowAlarm: "unverified: unmapped unit type, read with the generic v7 reading",
        WaterTemperature: "unverified: unmapped unit type, read with the generic v7 reading",
    },
)
