name: Validate

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feat/device-profiles
  pull_request:
    branches:
      - main
      - feat/device-profiles

permissions: {}

jobs:
  hassfest: # https://developers.home-assistant.io/blog/2020/04/16/hassfest
    name: Hassfest validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7

      - name: Run hassfest validation
        uses: home-assistant/actions/hassfest@master

  hacs: # https://github.com/hacs/action
    name: HACS validation
    runs-on: ubuntu-latest
    if: github.repository == 'hopkins-tk/home-assistant-aseko-local'
    steps:
      - name: Run HACS validation
        uses: hacs/action@main
        with:
          category: integration

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --requirement requirements.txt --requirement requirements.test.txt
      - name: Run tests
        run: |
          python -m pytest --timeout=10 tests
